Repository sendbird/sendbird-uikit-react, pull requests merged in 2023-06, with the labels that each got.

#576 fix: Apply theme to MobileBottomSheet
  src/ui/MobileMenu/MobileBottomSheet.tsx
Labels: Ready for review

#577 fix: display message status on mobile
  src/ui/MessageContent/index.scss
Labels: Ready for review

#560 chore: Add dataId to the every menu items
  src/modules/ChannelList/components/ChannelPreviewAction.jsx
  src/modules/ChannelSettings/components/ModerationPanel/BannedUserList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
  src/modules/OpenChannelSettings/components/OperatorUI/BannedUserList.tsx
  src/modules/OpenChannelSettings/components/OperatorUI/BannedUsersModal.tsx
  src/modules/OpenChannelSettings/components/OperatorUI/MutedParticipantList.tsx
  src/modules/OpenChannelSettings/components/OperatorUI/MutedParticipantsModal.tsx
  src/modules/OpenChannelSettings/components/OperatorUI/OperatorList.tsx
  src/modules/OpenChannelSettings/components/OperatorUI/OperatorsModal.tsx
  src/modules/OpenChannelSettings/components/ParticipantUI/ParticipantsModal.tsx
  src/modules/OpenChannelSettings/components/ParticipantUI/index.tsx
  src/ui/ContextMenu/index.tsx
  src/ui/EmojiReactions/index.tsx
  src/ui/MessageItemMenu/index.tsx
  src/ui/MessageItemReactionMenu/index.tsx
  src/ui/MobileMenu/MobileBottomSheet.tsx
  src/ui/MobileMenu/MobileContextMenu.tsx
  src/ui/MobileMenu/MobileEmojisBottomSheet.tsx
  src/ui/OpenChannelMobileMenu/index.tsx
  src/ui/OpenchannelFileMessage/index.tsx
  src/ui/OpenchannelOGMessage/index.tsx
  src/ui/OpenchannelThumbnailMessage/index.tsx
  src/ui/OpenchannelUserMessage/index.tsx
  src/ui/ReactionButton/__tests__/ReactionButton.spec.js
  src/ui/ReactionButton/__tests__/__snapshots__/ReactionButton.spec.js.snap
  src/ui/ReactionButton/index.tsx
Labels: Ready for review

#578 feat: Rename MediaQueryBreakpoint to breakpoint
  scripts/index_d_ts
  src/lib/MediaQueryContext.tsx
  src/lib/Sendbird.tsx
  src/modules/App/index.jsx
Labels: Ready for review

#579 fix: Flexible thumbnail width
  src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
  src/ui/MessageContent/index.tsx
Labels: Ready for review

#582 fix: Prevent hover style of ParentMessageInfo comp
  src/modules/Thread/components/ParentMessageInfo/index.scss
Labels: Ready for review

#581 fix: Provide markAsDeliveredScheduler from SendbirdProvider
  src/lib/Sendbird.tsx
Labels: Ready for review

#583 fix: Reactions width on mobile
  src/modules/Thread/components/ThreadList/ThreadListItemContent.scss
Labels: Ready for review

#587 fix: Use short muted message in message input of mobile mode
  src/modules/Channel/components/MessageInput/index.tsx
Labels: Ready for review

#588 fix: Add border bottom to the ParentMessageInfo component
  src/modules/Thread/components/ThreadUI/index.scss
Labels: Ready for review

#589 fix: Remove edited message from ChannelPreview
  src/modules/ChannelList/components/ChannelPreview/index.tsx
Labels: Ready for review

#590 fix: Disable mention in the broadcast channel
  src/modules/Channel/components/MessageInput/index.tsx
  src/modules/Thread/components/ThreadMessageInput/index.tsx
Labels: Ready for review

#585 feat: add UIKitConfigStorageManager
  src/lib/UIKitConfigProvider/UIKitConfigStorageManager/__tests__/index.spec.ts
  src/lib/UIKitConfigProvider/UIKitConfigStorageManager/index.ts
  src/lib/UIKitConfigProvider/const/initialConfig.ts
  src/lib/UIKitConfigProvider/index.tsx
Labels: Ready for review

#591 fix: Improve MobileContextMenu
  src/ui/MobileMenu/MobileContextMenu.tsx
Labels: Ready for review

#584 fix: apply ellipsis to quote and admin msg
  src/ui/AdminMessage/index.scss
  src/ui/MessageContent/index.scss
  src/ui/MessageContent/index.tsx
  src/ui/QuoteMessage/index.scss
Labels: Ready for review

#592 fix: Change OpenChannelInput muted state notice text
  src/modules/OpenChannel/components/OpenChannelInput/index.tsx
Labels: Ready for review

#594 chore: Add a sample with router
  samples/router/.eslintrc.cjs
  samples/router/.gitignore
  samples/router/index.html
  samples/router/package-lock.json
  samples/router/package.json
  samples/router/public/vite.svg
  samples/router/src/App.tsx
  samples/router/src/assets/react.svg
  samples/router/src/index.css
  samples/router/src/main.tsx
  samples/router/src/routes/Channel.tsx
  samples/router/src/routes/ChannelList.tsx
  samples/router/src/routes/ChannelSettings.tsx
  samples/router/src/routes/Error.tsx
  samples/router/src/routes/MessageSearch.tsx
  samples/router/src/vite-env.d.ts
  samples/router/tsconfig.json
  samples/router/tsconfig.node.json
  samples/router/vite.config.ts
  scripts/index_d_ts
Labels: Ready for review

#593 fix: Donot show download option in super and broadcast channels
  src/ui/MobileMenu/MobileContextMenu.tsx
Labels: Ready for review

#597 hotfix: TSC error in typescript sample
  samples/typescript_sample/src/App.tsx
Labels: Ready for review

#596 fix: clarify the meaning of isParentMessage
  src/utils/__tests__/isParentMessage.spec.ts
  src/utils/index.ts
Labels: Ready for review

#599 fix: Hide download option for only voice message
  src/ui/MobileMenu/MobileContextMenu.tsx
Labels: Ready for review

#600 fix: Emoji reactions overflow in thread
  src/modules/Thread/components/ThreadList/ThreadListItemContent.scss
  src/ui/ThumbnailMessageItemBody/index.scss
Labels: Ready for review

#598 feat: Modify replyType & isVoiceMessageEnabled default value
  src/lib/Sendbird.tsx
  src/modules/App/index.jsx
  src/modules/App/stories/index.stories.js
Labels: Ready for review

#603 feat: Apply enableOgtag config set from Dashboard
  src/lib/Sendbird.tsx
  src/lib/UIKitConfigProvider/index.tsx
  src/lib/UIKitConfigProvider/types.ts
  src/lib/types.ts
  src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
  src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
  src/ui/MessageContent/__tests__/MessageContent.spec.js
  src/ui/MessageContent/index.tsx
  src/utils/index.ts
Labels: Ready for review

#601 fix: Remove loading placeholder on image
  src/ui/ThumbnailMessageItemBody/__tests__/ThumbnailMessageItemBody.spec.js
  src/ui/ThumbnailMessageItemBody/__tests__/__snapshots__/ThumbnailMessageItemBody.spec.js.snap
  src/ui/ThumbnailMessageItemBody/index.tsx
Labels: Ready for review

#611 fix: Show context menu on click
  src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
Labels: Ready for review

#608 fix: Race condition in playing audio file
  src/hooks/VoicePlayer/index.tsx
Labels: Ready for review

#609 fix: Stop voice player when recorder exits
  src/modules/Channel/components/MessageInput/VoiceMessageInputWrapper.tsx
Labels: Ready for review

#606 fix: Pause voice when moved back
  src/hooks/VoicePlayer/index.tsx
  src/modules/App/MobileLayout.tsx
  src/ui/VoiceMessageItemBody/index.tsx
Labels: Ready for review

#605 feat: Show warning when there is no voice permission
  src/hooks/VoiceRecorder/index.tsx
  src/ui/Label/stringSet.js
Labels: Ready for review

#607 fix: Triggering random clicks while scroll to parent
  src/modules/Channel/context/hooks/useScrollToMessage.ts
  src/ui/QuoteMessage/index.tsx
Labels: Ready for review

#610 fix: OpenChannel Context menu click leak
  src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
  src/modules/OpenChannel/components/OpenChannelMessage/utils.ts
  src/ui/OpenchannelFileMessage/index.tsx
  src/ui/OpenchannelOGMessage/index.tsx
  src/ui/OpenchannelThumbnailMessage/index.tsx
  src/ui/OpenchannelUserMessage/index.tsx
Labels: Ready for review

#614 feat: replace local uikitConfigProvider \w uikit-tools one
  package.json
  rollup.config.js
  src/lib/Sendbird.tsx
  src/lib/UIKitConfigProvider/UIKitConfigStorageManager/__tests__/index.spec.ts
  src/lib/UIKitConfigProvider/UIKitConfigStorageManager/index.ts
  src/lib/UIKitConfigProvider/const/initialConfig.ts
  src/lib/UIKitConfigProvider/index.tsx
  src/lib/UIKitConfigProvider/types.ts
  src/lib/UIKitConfigProvider/utils/__tests__/getConfigsByPriority.spec.ts
  src/lib/UIKitConfigProvider/utils/__tests__/snakeToCamel.spec.ts
  src/lib/UIKitConfigProvider/utils/__tests__/type.spec.ts
  src/lib/UIKitConfigProvider/utils/getConfigsByPriority.ts
  src/lib/UIKitConfigProvider/utils/snakeToCamel.ts
  src/lib/UIKitConfigProvider/utils/types.ts
  src/lib/types.ts
  src/lib/utils/__tests__/resolvedReplyType.spec.ts
  src/lib/utils/resolvedReplyType.ts
  yarn.lock
Labels: Ready for review

#616 feat: apply groupchannel enableMessageSearch config flag
  scripts/index_d_ts
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/modules/App/index.jsx
  src/modules/Channel/context/ChannelProvider.tsx
Labels: Ready for review

#617 feat: apply groupChannel.enableTypingIndicator config flag
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/modules/Channel/components/ChannelUI/index.tsx
Labels: Ready for review

#618 feat: Open prop breakpoint
  scripts/index_d_ts
  src/lib/MediaQueryContext.tsx
  src/lib/Sendbird.tsx
  src/modules/App/index.jsx
Labels: Ready for review

#622 chore: Samples -> Upgrade vite to 4.3.9
  samples/groupchannel/package-lock.json
  samples/groupchannel/package.json
  samples/openchannel/package-lock.json
  samples/openchannel/package.json
  samples/typescript_sample/package-lock.json
  samples/typescript_sample/package.json
Labels: Ready for review

#623 feat: reset default value of duplicated configs in modules/App
  src/modules/App/index.jsx
Labels: Ready for review

#625 fix: Desktop - allow text select on Labels
  src/ui/Label/index.scss
Labels: Ready for review

#613 feat: apply xxChannel.input.enableDocument dashboard config
  scripts/index_d_ts
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/modules/Channel/components/Message/index.tsx
  src/modules/OpenChannel/components/OpenChannelInput/index.tsx
  src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
  src/modules/Thread/components/ParentMessageInfo/index.tsx
  src/modules/Thread/components/ThreadList/ThreadListItem.tsx
  src/ui/MessageInput/__tests__/MessageInput.spec.js
  src/ui/MessageInput/index.jsx
  src/ui/MessageInput/messageInputUtils.ts
Labels: Ready for review

#627 fix: OGMessage width while adding reaction
  src/ui/OGMessageItemBody/index.scss
Labels: Ready for review

#629 fix: Mobile layout / Navigation on DM from Thread
  scripts/index_d_ts
  src/modules/App/MobileLayout.tsx
  src/modules/Thread/context/ThreadProvider.tsx
Labels: Ready for review

#630 feat: make integrated toggle config options resettable
  src/lib/Sendbird.tsx
  src/modules/App/stories/integrated-app.scss
  src/modules/App/stories/integrated.stories.js
Labels: Ready for review

#631 fix: Thread / Add extra state to show/hide delete menu
  src/modules/Thread/components/ParentMessageInfo/index.tsx
  src/ui/MobileMenu/MobileBottomSheet.tsx
  src/ui/MobileMenu/MobileContextMenu.tsx
  src/ui/MobileMenu/index.tsx
  src/ui/MobileMenu/types.ts
Labels: help wanted, Ready for review

#632 fix: vertical scroll on labels in open channel list
  src/modules/OpenChannelList/components/OpenChannelPreview/index.scss
Labels: Ready for review

#633 fix: Center align & remove ellipsis from admin message
  src/ui/AdminMessage/index.scss
Labels: Ready for review

#635 fix: Quoted text alignment for reply outgoing message
  src/modules/App/stories/index.stories.js
  src/ui/QuoteMessage/index.scss
Labels: Ready for review

#636 feat: make sdk disconnected on Sendbird component umount
  src/hooks/useUnmount.ts
  src/lib/Sendbird.tsx
Labels: Ready for review

#638 fix: use global config's replyType if channel one is undefined
  src/modules/Channel/context/ChannelProvider.tsx
Labels: Ready for review

#640 fix: set fallback values \w global configs in App comp
  src/modules/App/AppLayout.tsx
Labels: Ready for review

#639 fix: use global disableUserProfile if each context's one is defined
  src/modules/Channel/context/ChannelProvider.tsx
  src/modules/ChannelList/context/ChannelListProvider.tsx
  src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
  src/modules/OpenChannel/context/OpenChannelProvider.tsx
  src/modules/OpenChannelSettings/context/OpenChannelSettingsProvider.tsx
  src/modules/Thread/context/ThreadProvider.tsx
Labels: Ready for review

#637 fix: Clear scrollToMessage on loading
  src/modules/Channel/components/MessageList/hooks/__test__/useSetScrollToBottom.spec.tsx
  src/modules/Channel/components/MessageList/hooks/useSetScrollToBottom.ts
  src/modules/Channel/components/MessageList/index.tsx
Labels: Ready for review

#641 fix: runtime error on accessing null parentMessage data
  src/ui/MessageContent/index.tsx
Labels: Ready for review

#643 fix: Handle undefined message type in is voice message
  src/utils/__tests__/isVoiceMessage.spec.ts
  src/utils/index.ts
Labels: Ready for review

#645 release: Release UIKit React v3.5.1
  CHANGELOG.md
  bundle-analysis.json
  package.json
  yarn.lock
Labels: Ready for review

#634 chore: Add sample to reroute when customer is banned
  samples/router/README.md
  samples/router/package-lock.json
  samples/router/package.json
  samples/router/src/App.css
  samples/router/src/App.tsx
  samples/router/src/DesktopLayout/Channel.tsx
  samples/router/src/DesktopLayout/ChannelList.tsx
  samples/router/src/DesktopLayout/ChannelSettings.tsx
  samples/router/src/DesktopLayout/MessageSearch.tsx
  samples/router/src/DesktopLayout/Router.tsx
  samples/router/src/Error.tsx
  samples/router/src/MobileLayout/Channel.tsx
  samples/router/src/MobileLayout/ChannelList.tsx
  samples/router/src/MobileLayout/ChannelSettings.tsx
  samples/router/src/MobileLayout/MessageSearch.tsx
  samples/router/src/MobileLayout/Router.tsx
  samples/router/src/hooks/useNavigateOnBan.ts
  samples/router/src/index.css
  samples/router/src/main.tsx
  samples/router/tsconfig.json
Labels: Ready for review

#647 chore: Remove react-dom/server from rollup.config
  rollup.config.js
Labels: Ready for review

#648 fix: Race condition in disconnect/connect
  src/lib/hooks/useConnect/__test__/setupConnection.spec.ts
  src/lib/hooks/useConnect/setupConnection.ts
Labels: Ready for review

#646 fix: Set offline class on body when disconnected
  src/lib/hooks/useOnlineStatus.js
Labels: Ready for review

#650 feat: add uikitOptions prop to App & SendbirdProvider
  src/index.d.ts
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/lib/utils/__tests__/uikitConfigMapper.spec.ts
  src/lib/utils/uikitConfigMapper.ts
  src/modules/App/index.jsx
  src/utils/typeHelpers/partialDeep.ts
Labels: Ready for review

#649 fix: Allow to reduce mobile app height
  src/modules/App/MobileLayout.tsx
  src/modules/App/mobile.scss
  src/modules/App/stories/index.stories.js
  src/modules/App/stories/utils.jsx
Labels: Ready for review

#652 fix: Prevent displaying unread count with empty unread since
  src/modules/Channel/components/MessageList/index.tsx
  src/modules/Channel/context/dux/initialState.js
Labels: Ready for review

#653 fix: Improve sampling and bitrate of Voice Recording
  src/hooks/VoiceRecorder/WebAudioUtils.ts
  src/hooks/VoiceRecorder/index.tsx
  src/utils/consts.ts
Labels: Ready for review

#654 fix: move scroll every time when message height changes
  src/modules/Channel/components/Message/index.tsx
  src/modules/Channel/components/MessageList/index.tsx
Labels: Ready for review

#656 release v3.5.2
  CHANGELOG.md
  bundle-analysis.json
  package.json
Labels: Ready for review

#642 doc: Improve IC guide in PR Template
  .github/pull_request_template.md
Labels: In Discussion

#658 feat: add gh workflow for auto release ticket creation
  .circleci/config.yml
  .github/workflows/release-ticket-creation.yml
Labels: Ready for review

#660 fix: incorrect Circle CI secret env name
  .github/workflows/release-ticket-creation.yml
Labels: Ready for review

#655 docs: add UIKit Configuration sample guide
  SAMPLES.md
Labels: Ready for review

#662 release: v3.6.0 - official feature config support
  CHANGELOG.md
  SAMPLES.md
  bundle-analysis.json
  package.json
Labels: Ready for review

#659 feat: Keep keyboard open after sending the message
  src/ui/MessageInput/index.jsx
Labels: Ready for review

#663 chore: Correct the repo for e2e testing
  scripts/steps.md
Labels: Ready for review

#665 feat: enable channel creation for logged-in user only
  src/modules/CreateChannel/components/InviteUsers/index.tsx
Labels: Ready for review

#668 fix: UIKit@3.6.0 build error on CRA
  package.json
  yarn.lock
Labels: Ready for review
