Repository sendbird/sendbird-uikit-react, pull requests merged in 2023-12, with the labels that each got.

#879 bug-fix: Fixed a bug where resending MFM fails in thread.
  src/modules/Channel/context/ChannelProvider.tsx
  src/modules/Channel/context/dux/reducers.ts
  src/modules/Channel/context/hooks/useResendMessageCallback.ts
  src/modules/Channel/context/hooks/useSendMultipleFilesMessage.ts
  src/modules/Thread/context/dux/reducer.ts
  src/modules/Thread/context/hooks/useResendMessageCallback.ts
Labels: v3.9.1

#882 fix: Remove left 0px from Avatar comp to fix ruined align
  src/ui/Avatar/__tests__/__snapshots__/Avatar.spec.js.snap
  src/ui/Avatar/index.tsx
  src/ui/FileViewer/__tests__/__snapshots__/FileViewer.spec.js.snap
  src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
  src/ui/MessageSearchFileItem/__tests__/__snapshots__/MessageSearchFileItem.spec.js.snap
  src/ui/MessageSearchItem/__tests__/__snapshots__/MessageSearchItem.spec.js.snap
  src/ui/OpenchannelConversationHeader/__tests__/__snapshots__/OpenchannelConversationHeader.spec.js.snap
  src/ui/OpenchannelFileMessage/__tests__/__snapshots__/OpenchannelFileMessage.spec.js.snap
  src/ui/OpenchannelOGMessage/__tests__/__snapshots__/OpenchannelOGMessage.spec.js.snap
  src/ui/OpenchannelThumbnailMessage/__tests__/__snapshots__/OpenchannelThumbnailMessage.spec.js.snap
  src/ui/OpenchannelUserMessage/__tests__/__snapshots__/OpenchannelUserMessage.spec.js.snap
  src/ui/UserListItem/__tests__/__snapshots__/UserListItem.spec.js.snap
Labels: Ready for review, v3.9.1

#881 bug-fix: Group channel user left or banned event should not be ignored
  src/modules/Channel/context/hooks/useHandleChannelEvents.ts
Labels: v3.9.1

#880 fix: Divide the EditUserProfileUI to Modal and View parts
  src/modules/ChannelList/components/ChannelListUI/index.tsx
  src/modules/ChannelSettings/components/UserListItem/index.tsx
  src/modules/ChannelSettings/components/UserListItem/user-list-item.scss
  src/modules/EditUserProfile/components/EditUserProfileUI/EditUserProfileUIView.tsx
  src/modules/EditUserProfile/components/EditUserProfileUI/index.tsx
  src/modules/OpenChannelSettings/components/ParticipantUI/ParticipantItem.tsx
  src/modules/Thread/components/ParentMessageInfo/index.tsx
  src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
  src/types.ts
  src/ui/MessageContent/MessageProfile/index.tsx
  src/ui/OpenchannelFileMessage/index.tsx
  src/ui/OpenchannelOGMessage/index.tsx
  src/ui/OpenchannelThumbnailMessage/index.tsx
  src/ui/OpenchannelUserMessage/index.tsx
  src/ui/UserListItem/index.tsx
Labels: Ready for review, v3.9.1

#884 bug-fix: Fixed a bug where admin message disappears when sending a message
  src/modules/Channel/context/dux/reducers.ts
Labels: v3.9.1

#888 fix: Use PropsWithChildren<unknown> instead PropsWithChildren
  src/hooks/useModal/index.tsx
  src/lib/Sendbird.tsx
Labels: Ready for review, v3.9.2

#889 fix: the reset text appears in the next input
  src/ui/MessageInput/index.tsx
  src/utils/__tests__/utils.spec.ts
  src/utils/utils.ts
Labels: v3.9.2

#891 fix: Clean up CSS files between Channel and GroupChannel
  src/modules/Channel/components/ChannelHeader/index.tsx
  src/modules/Channel/components/ChannelUI/index.tsx
  src/modules/Channel/components/FileViewer/index.tsx
  src/modules/Channel/components/FrozenNotification/index.tsx
  src/modules/Channel/components/MessageInput/VoiceMessageInputWrapper.tsx
  src/modules/Channel/components/MessageInput/index.tsx
  src/modules/Channel/components/MessageInput/voice-message-wrapper.scss
  src/modules/Channel/components/MessageList/index.tsx
  src/modules/Channel/components/SuggestedMentionList/index.scss
  src/modules/Channel/components/SuggestedMentionList/index.tsx
  src/modules/Channel/components/SuggestedReplies/index.scss
  src/modules/Channel/components/SuggestedReplies/index.tsx
  src/modules/Channel/components/UnreadCount/index.tsx
  src/modules/GroupChannel/components/ChannelHeader/index.scss
  src/modules/GroupChannel/components/ChannelHeader/index.tsx
  src/modules/GroupChannel/components/ChannelUI/index.scss
  src/modules/GroupChannel/components/ChannelUI/index.tsx
  src/modules/GroupChannel/components/FileViewer/index.scss
  src/modules/GroupChannel/components/FileViewer/index.tsx
  src/modules/GroupChannel/components/FrozenNotification/index.scss
  src/modules/GroupChannel/components/FrozenNotification/index.tsx
  src/modules/GroupChannel/components/MessageInput/VoiceMessageInputWrapper.tsx
  src/modules/GroupChannel/components/MessageInput/index.scss
  src/modules/GroupChannel/components/MessageInput/index.tsx
  src/modules/GroupChannel/components/MessageInput/voice-message-wrapper.scss
  src/modules/GroupChannel/components/MessageList/index.scss
  src/modules/GroupChannel/components/MessageList/index.tsx
  src/modules/GroupChannel/components/SuggestedMentionList/index.scss
  src/modules/GroupChannel/components/SuggestedReplies/index.scss
  src/modules/GroupChannel/components/UnreadCount/index.scss
  src/modules/GroupChannel/components/UnreadCount/index.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
Labels: Collection

#897 fix: Include metaArray to messages when reconnecting
  src/hooks/VoicePlayer/useVoicePlayer.tsx
  src/lib/hooks/useOnlineStatus.ts
  src/modules/Channel/context/hooks/useHandleReconnect.ts
Labels: v3.9.2

#899 refactor: move --sendbird-vh css variable setting logic to comp
  src/modules/App/MobileLayout.tsx
  src/modules/CreateChannel/components/InviteUsers/index.tsx
  src/modules/CreateChannel/components/InviteUsers/invite-users.scss
Labels: Ready for review

#902 fix: replay voice memos
  src/hooks/VoicePlayer/dux/reducer.ts
Labels: Ready for review
