Repository sendbird/sendbird-uikit-react, pull requests merged in 2023-11, with the labels that each got.

#828 fix: lastMessage is nullable
  src/modules/Channel/components/Message/index.tsx
  src/utils/__tests__/getSuggestedReplies.spec.ts
  src/utils/index.ts
Labels: Ready for review

#829 feat: export initialMessagesFetch callback from hook
  rollup.module-exports.mjs
  src/modules/Channel/context/hooks/useInitialMessagesFetch.ts
Labels: Ready for review

#831 fix: precise object dependency in effect hook
  src/modules/ChannelList/context/ChannelListProvider.tsx
Labels: Ready for review

#834 Release v3.8.0
  CHANGELOG.md
  package.json
Labels: Ready for review

#839 fix: Improve Image Compression feature
  src/modules/Channel/components/MessageInput/index.tsx
  src/modules/Channel/components/MessageInput/useHandleUploadFiles.tsx
  src/modules/Channel/context/hooks/useSendFileMessageCallback.ts
  src/modules/Thread/components/ThreadMessageInput/index.tsx
  src/utils/compressImages.ts
  src/utils/pxToNumber.ts
Labels: Ready for review

#842 chore: apply publishing module review
  src/modules/internalInterfaces.ts
Labels: v3.8.3

#846 feat: Add typing indicator types global option
  package.json
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/lib/utils/uikitConfigMapper.ts
  src/modules/App/stories/index.stories.js
  src/modules/App/stories/integrated.stories.js
  src/modules/Channel/components/ChannelUI/index.tsx
  src/modules/Channel/components/MessageList/index.tsx
  src/types.ts
  src/ui/TypingIndicatorMessage/index.tsx
  src/utils/typeHelpers/partialDeep.ts
  yarn.lock
Labels: v3.8.3

#851 feat: add eventHandler.connection.onFailed to handle connection error
  src/lib/Sendbird.tsx
  src/lib/hooks/useConnect/__test__/setupConnection.spec.ts
  src/lib/hooks/useConnect/connect.ts
  src/lib/hooks/useConnect/index.ts
  src/lib/hooks/useConnect/setupConnection.ts
  src/lib/hooks/useConnect/types.ts
  src/lib/types.ts
Labels: Ready for review, v3.8.3

#852 chore: Add changelogs section in PR template
  .github/pull_request_template.md
Labels: v3.8.3, internal

#855 fix: apply onProfileEditSuccess props
  src/modules/App/stories/integrated.stories.js
  src/modules/ChannelList/components/ChannelListUI/index.tsx
  src/modules/EditUserProfile/components/EditUserProfileUI/index.tsx
  src/modules/EditUserProfile/index.tsx
Labels: v3.8.3

#847 feat: scroll to the top of the target message element in Channel component
  src/modules/Channel/context/__test__/utils.spec.js
  src/modules/Channel/context/utils.ts
Labels: v3.8.3

#858 fix: Clear localMessages when initializing message list
  src/modules/Channel/context/dux/reducers.ts
Labels: Ready for review, v3.8.3

#854 feat: Support custom rendering message menus and reactions
  src/ui/EmojiReactions/index.tsx
  src/ui/MessageContent/MessageProfile/index.tsx
  src/ui/MessageContent/index.tsx
  src/ui/MessageItemMenu/index.tsx
  src/ui/MessageItemReactionMenu/index.tsx
Labels: Ready for review, v3.8.3

#856 feat: Added renderFrozenNotification in ChannelUIProps
  src/modules/App/stories/index.stories.js
  src/modules/Channel/components/ChannelUI/index.tsx
  src/modules/Channel/components/MessageList/index.tsx
  src/modules/Channel/index.tsx
Labels: v3.8.3

#838 feat: Update TypingIndicatorBubble to support multiple typing members
  package.json
  rollup.module-exports.mjs
  src/index.ts
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/lib/utils/uikitConfigMapper.ts
  src/modules/App/stories/index.stories.js
  src/modules/App/stories/integrated.stories.js
  src/modules/Channel/components/ChannelUI/index.tsx
  src/modules/Channel/components/MessageList/index.tsx
  src/types.ts
  src/ui/Avatar/AvatarDefault.tsx
  src/ui/Avatar/__tests__/__snapshots__/Avatar.spec.js.snap
  src/ui/Avatar/index.scss
  src/ui/Avatar/index.tsx
  src/ui/FileViewer/__tests__/__snapshots__/FileViewer.spec.js.snap
  src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
  src/ui/MessageContent/index.scss
  src/ui/MessageSearchFileItem/__tests__/__snapshots__/MessageSearchFileItem.spec.js.snap
  src/ui/MessageSearchItem/__tests__/__snapshots__/MessageSearchItem.spec.js.snap
  src/ui/OpenchannelConversationHeader/__tests__/__snapshots__/OpenchannelConversationHeader.spec.js.snap
  src/ui/OpenchannelFileMessage/__tests__/__snapshots__/OpenchannelFileMessage.spec.js.snap
  src/ui/OpenchannelOGMessage/__tests__/__snapshots__/OpenchannelOGMessage.spec.js.snap
  src/ui/OpenchannelThumbnailMessage/__tests__/__snapshots__/OpenchannelThumbnailMessage.spec.js.snap
  src/ui/OpenchannelUserMessage/__tests__/__snapshots__/OpenchannelUserMessage.spec.js.snap
  src/ui/TypingIndicatorBubble/TypingDots.tsx
  src/ui/TypingIndicatorBubble/__tests__/TypingIndicatorBubble.spec.js
  src/ui/TypingIndicatorBubble/index.tsx
  src/ui/TypingIndicatorBubble/typingDots.scss
  src/ui/TypingIndicatorMessage/index.tsx
  src/ui/UserListItem/__tests__/__snapshots__/UserListItem.spec.js.snap
  src/utils/typeHelpers/partialDeep.ts
  yarn.lock
Labels: v3.8.3

#859 fix: Fit the OGMessage Thumbnail Image to the minimal width length
  src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
  src/ui/OGMessageItemBody/index.tsx
Labels: Ready for review, v3.8.3

#860 fix: Do pubSub publish when resending message is succeeded
  src/modules/Thread/context/hooks/useResendMessageCallback.ts
Labels: Ready for review, v3.8.3

#864 feat: implement AddChannelView for presentation layer
  src/modules/ChannelList/components/AddChannel/index.tsx
  src/modules/GroupChannelList/components/AddChannel/AddChannelView.tsx
  src/modules/GroupChannelList/components/AddChannel/index.tsx
Labels: Collection

#865 feat: implement ChannelListUIView for presentation layer
  .eslintrc.json
  src/hooks/useOnScrollReachedEndDetector/index.ts
  src/modules/ChannelList/components/ChannelListUI/index.tsx
  src/modules/ChannelList/index.tsx
  src/modules/GroupChannelList/components/ChannelListUI/ChannelListUIView.tsx
  src/modules/GroupChannelList/components/ChannelListUI/index.tsx
  src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
  src/modules/GroupChannelList/stories/index.stories.tsx
Labels: Collection

#866 feat: Replace the ChannelListHeader comp to the GroupChannelListHeader comp
  src/modules/ChannelList/components/ChannelListHeader/index.scss
  src/modules/ChannelList/components/ChannelListHeader/index.tsx
  src/modules/GroupChannelList/components/ChannelListHeader/index.tsx
  src/modules/GroupChannelList/components/ChannelListUI/ChannelListUIView.tsx
  src/modules/GroupChannelList/components/GroupChannelListHeader/index.scss
  src/modules/GroupChannelList/components/GroupChannelListHeader/index.tsx
Labels: Collection

#871 chore: update gcc components naming
  src/modules/ChannelList/components/AddChannel/index.tsx
  src/modules/ChannelList/components/ChannelListUI/channel-list-ui.scss
  src/modules/ChannelList/components/ChannelListUI/index.tsx
  src/modules/ChannelList/components/ChannelPreview/channel-preview.scss
  src/modules/GroupChannelList/components/AddGroupChannel/AddGroupChannelView.tsx
  src/modules/GroupChannelList/components/AddGroupChannel/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListHeader/index.scss
  src/modules/GroupChannelList/components/GroupChannelListItem/index.scss
  src/modules/GroupChannelList/components/GroupChannelListItem/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListUI/GroupChannelListUIView.tsx
  src/modules/GroupChannelList/components/GroupChannelListUI/index.scss
  src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx
  src/modules/GroupChannelList/components/GroupChannelPreviewAction.tsx
  src/modules/GroupChannelList/index.tsx
Labels: Collection

#872 fix: Apply StringSet for the file upload limit notification
  src/modules/Channel/components/MessageInput/useHandleUploadFiles.tsx
  src/ui/Label/stringSet.ts
Labels: v3.9.1

#876 fix: Complete GroupChannelList props interface
  package.json
  src/modules/App/stories/index.stories.js
  src/modules/ChannelList/context/ChannelListProvider.tsx
  src/modules/ChannelList/utils.ts
  src/modules/GroupChannelList/components/AddGroupChannel/AddGroupChannelView.tsx
  src/modules/GroupChannelList/components/AddGroupChannel/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx
  src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
  src/modules/GroupChannelList/index.tsx
  yarn.lock
Labels: Collection

#874 fix: Add a message prop to the ReactionItem comp
  src/ui/EmojiReactions/ReactionItem.tsx
  src/ui/EmojiReactions/index.tsx
Labels: v3.9.1
