Repository sendbird/sendbird-uikit-react, pull requests merged in 2024-09, with the labels that each got.

#1214 [CLNP-5022] feat: add message input related eventHandlers
  src/lib/types.ts
  src/ui/MessageInput/__tests__/MessageInput.spec.js
  src/ui/MessageInput/index.tsx
Labels: 3.15.2

#1219 [CLNP-5111] feat: replace sdk.disconnect -> sdk.disconnectWebsocket
  src/lib/Sendbird.tsx
  src/lib/hooks/useConnect/__test__/data.mocks.ts
  src/lib/hooks/useConnect/__test__/disconnectSdk.spec.ts
  src/lib/hooks/useConnect/disconnectSdk.ts
Labels: 3.15.3

#1217 [CLNP-5095] fix: ignore RTL handling - checkbox style
  src/ui/Checkbox/index.scss
Labels: 3.15.3

#1221 feature: Add string set for date format
  src/modules/Channel/context/dux/__tests__/reducers.spec.js
  src/modules/Channel/context/dux/reducers.ts
  src/modules/Channel/context/utils.ts
  src/modules/GroupChannel/components/MessageList/__test__/getMessagePartsInfo.spec.js
  src/modules/GroupChannelList/components/GroupChannelListItem/utils.ts
  src/modules/OpenChannel/context/utils.ts
  src/modules/Thread/components/ParentMessageInfo/index.tsx
  src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
  src/modules/Thread/context/utils.ts
  src/ui/Label/stringSet.ts
  src/ui/MessageContent/__tests__/MessageContent.spec.js
  src/ui/MessageContent/index.tsx
  src/ui/MessageSearchFileItem/__tests__/MessageSearchFileItem.spec.js
  src/ui/MessageSearchFileItem/utils.ts
  src/ui/MessageSearchItem/__tests__/MessageSearchItem.spec.js
  src/ui/MessageSearchItem/getCreatedAt.ts
  src/ui/MessageStatus/index.tsx
  src/ui/OpenchannelFileMessage/index.tsx
  src/ui/OpenchannelOGMessage/index.tsx
  src/ui/OpenchannelThumbnailMessage/index.tsx
  src/ui/OpenchannelUserMessage/index.tsx
  src/utils/messages.ts
Labels: 3.15.4

#1222 release: v3.15.4
  CHANGELOG.md
  package.json
Labels: 3.15.4
