Repository sendbird/sendbird-uikit-react, pull requests merged in 2024-04, with the labels that each got.

#1034 spec-change: Move timestamp to bottom left for carousel
  src/ui/MessageContent/index.scss
Labels: 3.14.0

#1035 feat: support carousel template with simple templates
  src/lib/dux/appInfo/utils.ts
  src/ui/MessageContent/MessageBody/index.tsx
  src/ui/MessageContent/index.tsx
  src/ui/MessageTemplate/messageTemplateErrorBoundary.tsx
  src/ui/TemplateMessageItemBody/index.tsx
  src/ui/TemplateMessageItemBody/types.ts
  src/utils/index.ts
Labels: 3.14.0

#1036 bug-fix: fix template qa issues
  src/ui/Avatar/__tests__/__snapshots__/Avatar.spec.js.snap
  src/ui/ChannelAvatar/__tests__/ChannelAvatar.spec.js
  src/ui/ImageRenderer/index.tsx
  src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
  src/ui/MessageContent/index.scss
  src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
Labels: 3.14.0

#1038 bug-fix: Fix bug where argb conversion step is skipped for carousel without reservation key
  src/ui/TemplateMessageItemBody/index.tsx
Labels: 3.14.0

#1039 bug-fix: Fix carousel template parent classname not applied
  package.json
  src/ui/MessageTemplate/index.tsx
  yarn.lock
Labels: 3.14.0

#1040 fix: Improve the Channel Settings Accordion Stability
  .storybook/preview-head.html
  src/modules/ChannelSettings/components/ModerationPanel/MemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/index.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/ui/Accordion/Accordion.tsx
  src/ui/Accordion/AccordionGroup.tsx
  src/ui/Accordion/index.scss
  src/ui/Accordion/index.tsx
  src/ui/OGMessageItemBody/index.tsx
  src/ui/UserListItem/index.tsx
Labels: 3.13.5

#1041 release: v3.13.5
  CHANGELOG.md
  package.json
Labels: 3.13.5

#1044 Merge v3.14.0-beta-1 to main!
  CHANGELOG.md
  package.json
  scripts/steps.md
  src/lib/dux/appInfo/actionTypes.ts
  src/lib/dux/appInfo/initialState.ts
  src/lib/dux/appInfo/reducers.ts
  src/lib/dux/appInfo/utils.ts
  src/lib/hooks/useMessageTemplateUtils.ts
  src/lib/types.ts
  src/modules/GroupChannel/components/MessageList/index.scss
  src/modules/GroupChannel/components/MessageList/index.tsx
  src/modules/GroupChannel/components/MessageTemplateWrapper/index.tsx
  src/types.ts
  src/ui/Avatar/__tests__/__snapshots__/Avatar.spec.js.snap
  src/ui/Avatar/index.tsx
  src/ui/Carousel/index.scss
  src/ui/Carousel/index.tsx
  src/ui/ChannelAvatar/__tests__/ChannelAvatar.spec.js
  src/ui/ImageRenderer/index.tsx
  src/ui/Label/index.tsx
  src/ui/MessageContent/MessageBody/index.tsx
  src/ui/MessageContent/MessageProfile/index.tsx
  src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
  src/ui/MessageContent/index.scss
  src/ui/MessageContent/index.tsx
  src/ui/MessageTemplate/index.scss
  src/ui/MessageTemplate/index.tsx
  src/ui/MessageTemplate/messageTemplateErrorBoundary.tsx
  src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
  src/ui/TemplateMessageItemBody/index.tsx
  src/ui/TemplateMessageItemBody/types.ts
  src/ui/TemplateMessageItemBody/utils/mapData.ts
  src/ui/TemplateMessageItemBody/utils/selectColorVariablesByTheme.ts
  src/ui/ThreadReplies/index.tsx
  src/utils/index.ts
  yarn.lock
Labels: 3.14.0

#1045 v3.14.0
  package.json
Labels: 3.14.0

#1047 fix: Support optional customize functions returning null case
  src/modules/Channel/components/ChannelUI/index.tsx
  src/modules/Channel/components/MessageList/index.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
  src/modules/GroupChannel/components/GroupChannelUI/GroupChannelUIView.tsx
  src/modules/GroupChannel/components/GroupChannelUI/index.tsx
  src/modules/GroupChannel/components/Message/MessageView.tsx
  src/modules/GroupChannel/components/MessageList/index.tsx
  src/ui/MessageContent/index.tsx
  src/ui/MessageItemMenu/index.tsx
  src/utils/__tests__/utils.spec.ts
  src/utils/utils.ts
Labels: 3.14.1

#1048 chore: fix typo and unused css props
  src/modules/GroupChannel/components/GroupChannelUI/index.scss
  src/modules/GroupChannel/components/Message/MessageView.tsx
  src/modules/OpenChannel/components/OpenChannelUI/open-channel-ui.scss
  src/ui/ThreadReplies/index.scss
Labels: 3.14.1

#1049 fix: update open channel interface properly
  src/modules/Channel/context/hooks/useSendFileMessageCallback.ts
  src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
  src/modules/OpenChannel/components/OpenChannelMessageList/index.tsx
  src/modules/OpenChannel/components/OpenChannelUI/index.tsx
  src/modules/OpenChannel/context/hooks/useFileUploadCallback.tsx
  src/modules/OpenChannel/index.tsx
  src/modules/Thread/context/hooks/useSendFileMessage.ts
  src/modules/Thread/context/hooks/useSendVoiceMessageCallback.ts
  src/ui/MessageContent/index.tsx
  src/ui/QuoteMessageInput/QuoteMessageThumbnail.tsx
  src/utils/index.ts
Labels: 3.14.1

#1051 release v3.14.1
  CHANGELOG.md
  package.json
  yarn.lock
Labels: 3.14.1

#1058 fix: remove image section in og message if there is no og image
  src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
  src/ui/FileMessageItemBody/index.tsx
  src/ui/LinkLabel/index.tsx
  src/ui/OGMessageItemBody/__tests__/OGMessageItemBody.spec.js
  src/ui/OGMessageItemBody/__tests__/__snapshots__/OGMessageItemBody.spec.js.snap
  src/ui/OGMessageItemBody/index.tsx
  src/ui/OpenchannelFileMessage/index.tsx
  src/ui/OpenchannelOGMessage/index.tsx
  src/utils/utils.ts
Labels: 3.14.2

#1056 fix: Fixed a bug where right padding is added to messages sent by me
  src/modules/GroupChannel/components/MessageList/index.scss
  src/ui/MessageContent/index.scss
Labels: 3.14.2

#1065 release: v3.14.2
  CHANGELOG.md
  package.json
Labels: 3.14.2

#1067 chore: bumpup chat sdk version to latest
  package.json
  yarn.lock
Labels: 3.14.3

#1064 feat: Support setting output file type in image compression process
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/lib/utils/uikitConfigMapper.ts
  src/modules/OpenChannel/context/hooks/useFileUploadCallback.tsx
  src/utils/compressImages.ts
Labels: 3.14.3

#1068 fix: Set the message list padding with 12px in the mobile layout
  src/modules/GroupChannel/components/MessageInputWrapper/index.scss
  src/modules/GroupChannel/components/MessageList/index.scss
Labels: 3.14.3

#1070 fix: Add target subType to fileName in every case
  src/utils/compressImages.ts
Labels: 3.14.3

#1069 release: v3.14.3
  CHANGELOG.md
  package.json
Labels: 3.14.3
