Repository sendbird/sendbird-uikit-react, pull requests merged in 2024-02, with the labels that each got.

#951 bug-fix: Fix bug where `ChannelListUI` is not updated when network is reconnected
  src/modules/App/index.tsx
  src/modules/Channel/context/hooks/useHandleReconnectForChannelList.ts
  src/modules/ChannelList/context/ChannelListProvider.tsx
  src/modules/ChannelList/dux/actionTypes.ts
  src/modules/ChannelList/dux/reducers.ts
  src/modules/ChannelList/index.tsx
  src/modules/ChannelList/utils.ts
Labels: v3.10.2

#952 chore: apply review
  src/modules/App/DesktopLayout.tsx
  src/modules/App/MobileLayout.tsx
  src/modules/ChannelList/components/AddChannel/index.tsx
  src/modules/ChannelList/components/ChannelListUI/index.tsx
  src/modules/CreateChannel/components/InviteUsers/index.tsx
  src/modules/CreateChannel/context/CreateChannelProvider.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/GroupChannelList/components/AddGroupChannel/AddGroupChannelView.tsx
  src/modules/GroupChannelList/components/AddGroupChannel/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListUI/GroupChannelListUIView.tsx
  src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx
  src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
  src/modules/GroupChannelList/stories/index.stories.tsx
Labels: Collection

#954 chore: remove filterMessageList from GroupChannel module
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
Labels: Collection

#953 bug-fix: Fix a bug in ChannelList where activeChannelUrl is set but onChannelSelect fires with null after loading ChannelList
  src/modules/ChannelList/dux/__tests__/reducers.spec.js
  src/modules/ChannelList/dux/reducers.ts
Labels: v3.10.2

#955 fix: Add missing export for the group channel modules
  src/modules/GroupChannel/components/FrozenNotification/index.tsx
  src/modules/GroupChannel/components/GroupChannelUI/index.tsx
  src/modules/GroupChannel/components/RemoveMessageModal/RemoveMessageModalView.tsx
  src/modules/GroupChannel/components/RemoveMessageModal/index.tsx
  src/modules/GroupChannel/components/UnreadCount/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListItem/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx
  src/modules/GroupChannelList/components/GroupChannelPreviewAction.tsx
Labels: Collection

#956 chore: clean up GroupChannel and GroupChannelList modules
  src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/GroupChannel/context/__test__/utils.spec.js
  src/modules/GroupChannel/context/const.ts
  src/modules/GroupChannel/context/hooks/useMessageActions.ts
  src/modules/GroupChannel/context/hooks/usePreventDuplicateRequest.ts
  src/modules/GroupChannel/context/utils.ts
  src/modules/GroupChannel/index.tsx
  src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
  src/modules/GroupChannelList/index.tsx
  src/utils/typeHelpers/partialRequired.ts
Labels: Collection

#961 fix: parsing URL within special characters
  src/modules/Message/utils/tokens/__tests__/tokenizeMessage.spec.ts
  src/modules/Message/utils/tokens/__tests__/tokenizeUtils.spec.ts
  src/modules/Message/utils/tokens/tokenize.ts
  src/ui/Word/index.scss
  src/utils/index.ts
Labels: Ready for review

#957 feat: Apply lastMessage suggestedReplies disable chat input flag
  package.json
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/lib/utils/uikitConfigMapper.ts
  src/modules/App/stories/integrated.stories.js
  src/modules/Channel/components/ChannelUI/index.tsx
  src/modules/Channel/components/Message/index.tsx
  src/modules/Channel/components/MessageInputWrapper/index.tsx
  src/modules/GroupChannel/components/GroupChannelUI/index.tsx
  src/modules/GroupChannel/components/Message/index.tsx
  src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
  src/modules/GroupChannel/components/MessageInputWrapper/index.tsx
  src/utils/index.ts
  yarn.lock
Labels: v3.11.0

#963 fix: cannot delete property renderMessage of Object
  src/modules/GroupChannel/components/Message/MessageView.tsx
  src/utils/__tests__/omitObjectProperties.spec.ts
  src/utils/omitObjectProperty.ts
Labels: v3.10.2, v3.11.0

#964 v3.11.0
  CHANGELOG.md
  package.json
Labels: v3.11.0, release

#965 fix: should pass render props properly in channel module
  src/modules/Channel/components/ChannelUI/index.tsx
  src/modules/Channel/components/MessageList/index.tsx
  src/modules/GroupChannel/components/GroupChannelUI/GroupChannelUIView.tsx
  src/modules/GroupChannel/components/GroupChannelUI/index.tsx
Labels: v3.11.1

#967 updated steps.md
  scripts/steps.md
Labels: v3.11.1

#966 fix: acceptableMimeTypes to support web standard format.
  src/utils/__tests__/getMimeTypesUIKitAccepts.spec.ts
  src/utils/index.ts
Labels: v3.11.1

#968 v3.11.1
  CHANGELOG.md
  package.json
Labels: release, v3.11.1

#969 fix: do not disconnect and connect when the accessToken is changed
  src/lib/hooks/useConnect/index.ts
Labels: v3.12.0

#971 fix: mentionTemplate should be passed when mapped to sendMessage
  src/modules/Channel/components/MessageInputWrapper/index.tsx
  src/modules/GroupChannel/components/MessageInputWrapper/index.tsx
Labels: v3.12.0

#972 fix: avoid numbered top-level domain
  src/modules/Message/utils/tokens/__tests__/tokenizeUtils.spec.ts
  src/modules/Message/utils/tokens/tokenize.ts
  src/ui/Word/index.tsx
Labels: v3.12.0

#975 fix: ensure consistent scroll to bottom delay after message send in channel module
  src/modules/Channel/context/hooks/useHandleChannelEvents.ts
  src/modules/Channel/context/hooks/useHandleChannelPubsubEvents.ts
  src/modules/Channel/context/hooks/useHandleReconnect.ts
  src/modules/Channel/context/hooks/useInitialMessagesFetch.ts
  src/modules/Channel/context/hooks/useSendFileMessageCallback.ts
  src/modules/Channel/context/hooks/useSendMessageCallback.ts
  src/modules/Channel/context/hooks/useSendMultipleFilesMessage.ts
  src/modules/Channel/context/hooks/useSendVoiceMessageCallback.ts
  src/modules/Channel/context/utils.ts
  src/modules/Thread/context/hooks/useSendFileMessage.ts
  src/modules/Thread/context/hooks/useSendVoiceMessageCallback.ts
  src/utils/consts.ts
Labels: v3.12.0

#976 chore: prepare collection publish
  package.json
  rollup.module-exports.mjs
  src/lib/hooks/useConnect/__test__/setupConnection.spec.ts
  src/lib/hooks/useConnect/connect.ts
  src/lib/hooks/useConnect/setupConnection.ts
  src/modules/App/index.tsx
  src/modules/ChannelList/components/ChannelListHeader/index.scss
  src/modules/ChannelList/components/ChannelListUI/channel-list-ui.scss
  src/modules/ChannelList/components/ChannelListUI/index.tsx
  src/modules/ChannelList/components/ChannelPreview/channel-preview.scss
  src/modules/ChannelList/components/ChannelPreview/index.tsx
  src/modules/ChannelList/components/ChannelPreviewAction.tsx
  src/modules/GroupChannel/components/SuggestedReplies/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListItem/GroupChannelListItemView.tsx
  src/modules/GroupChannelList/components/GroupChannelListItem/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListUI/GroupChannelListUIView.tsx
  src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx
  src/modules/GroupChannelList/components/GroupChannelPreviewAction.tsx
  yarn.lock
Labels: v3.12.0

#978 v3.12.0
  CHANGELOG.md
  MIGRATION_COLLECTION.md
  package.json
  samples/groupchannel/package-lock.json
  samples/groupchannel/package.json
  samples/groupchannel/src/CustomizedApp.jsx
  samples/router/package-lock.json
  samples/router/package.json
  samples/router/src/DesktopLayout/Channel.tsx
  samples/router/src/DesktopLayout/ChannelList.tsx
  samples/router/src/MobileLayout/Channel.tsx
  samples/router/src/MobileLayout/ChannelList.tsx
  samples/typescript_sample/package-lock.json
  samples/typescript_sample/package.json
  samples/typescript_sample/src/App.tsx
  src/hooks/VoiceRecorder/index.tsx
  src/lib/Sendbird.tsx
  src/lib/VoiceMessageProvider.tsx
  src/lib/hooks/useConnect/index.ts
  src/lib/utils/uikitConfigStorage.ts
  src/ui/Label/stringSet.ts
  src/ui/UserListItem/index.tsx
Labels: v3.12.0

#981 fix: show loading placeholder when fetching channel in ChannelSettings
  src/hooks/useAsyncRequest.ts
  src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
  src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
Labels: 3.12.1

#983 refactor: update useAsyncRequest, ChannelSettingsProvider
  src/hooks/useAsyncRequest.ts
  src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
Labels: 3.12.1

#984 Improve MessageListParams interface in ChannelProvider
  src/modules/Channel/context/ChannelProvider.tsx
  src/modules/Channel/context/dux/actionTypes.ts
Labels: 3.12.1

#985 fix: Allow multiple line in the MessageInput of Mobile env
  src/modules/Channel/context/const.ts
  src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
  src/modules/Thread/components/ThreadMessageInput/index.tsx
  src/ui/MessageInput/index.tsx
  src/ui/MessageInput/utils.ts
Labels: 3.12.1

#989 fix: Apply string set for file upload size and count limit
  src/modules/GroupChannel/components/MessageInputWrapper/useHandleUploadFiles.tsx
Labels: 3.12.1

#988 fix: message render structure
  src/modules/Channel/components/ChannelUI/index.tsx
  src/modules/Channel/components/MessageInputWrapper/index.tsx
  src/modules/Channel/components/MessageList/index.tsx
  src/modules/GroupChannel/components/GroupChannelUI/GroupChannelUIView.tsx
  src/modules/GroupChannel/components/Message/MessageView.tsx
  src/modules/GroupChannel/components/MessageInputWrapper/index.tsx
  src/modules/GroupChannel/components/MessageList/index.tsx
Labels: 3.12.1

#991 v3.12.1
  CHANGELOG.md
  package.json
Labels: 3.12.1

#987 feat: Support real time add missing template in cache on template message render
  src/lib/Sendbird.tsx
  src/lib/dux/appInfo/actionTypes.ts
  src/lib/dux/appInfo/initialState.ts
  src/lib/dux/appInfo/reducers.ts
  src/lib/dux/appInfo/utils.ts
  src/lib/hooks/useConnect/connect.ts
  src/lib/hooks/useConnect/index.ts
  src/lib/hooks/useConnect/setupConnection.ts
  src/lib/hooks/useConnect/types.ts
  src/lib/hooks/useMessageTemplateUtils.ts
  src/lib/hooks/useTheme.ts
  src/lib/types.ts
  src/modules/App/stories/index.stories.js
  src/modules/GroupChannel/components/MessageTemplateProvider/index.tsx
  src/modules/GroupChannel/context/hooks/temp.ts
  src/modules/GroupChannel/context/hooks/useMessageActions.ts
  src/styles/_color-themes.scss
  src/styles/_dark-theme.scss
  src/styles/_light-theme.scss
  src/ui/Icon/colors.ts
  src/ui/Icon/index.scss
  src/ui/Icon/utils.ts
  src/ui/Label/index.scss
  src/ui/Label/stringSet.ts
  src/ui/Label/types.ts
  src/ui/Label/utils.ts
  src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
  src/ui/MessageContent/index.scss
  src/ui/MessageContent/index.tsx
  src/ui/TemplateMessageItemBody/index.scss
  src/ui/TemplateMessageItemBody/index.tsx
  src/ui/TemplateMessageItemBody/types.ts
  src/utils/index.ts
Labels: SocarRequestedFeatures, MessageTemplate, 3.13.0

#982 Chore/improve template parsing logic
  jest.config.js
  package.json
  src/lib/Sendbird.tsx
  src/lib/dux/appInfo/actionTypes.ts
  src/lib/dux/appInfo/initialState.ts
  src/lib/dux/appInfo/reducers.ts
  src/lib/dux/appInfo/utils.ts
  src/lib/hooks/useConnect/connect.ts
  src/lib/hooks/useConnect/index.ts
  src/lib/hooks/useConnect/setupConnection.ts
  src/lib/hooks/useConnect/types.ts
  src/lib/hooks/useMessageTemplateUtils.ts
  src/lib/hooks/useTheme.ts
  src/lib/types.ts
  src/modules/App/stories/index.stories.js
  src/modules/App/types.ts
  src/modules/GroupChannel/components/MessageTemplateProvider/index.tsx
  src/modules/GroupChannel/context/hooks/temp.ts
  src/modules/GroupChannel/context/hooks/useMessageActions.ts
  src/styles/_color-themes.scss
  src/styles/_dark-theme.scss
  src/styles/_light-theme.scss
  src/ui/Icon/colors.ts
  src/ui/Icon/index.scss
  src/ui/Icon/utils.ts
  src/ui/Label/index.scss
  src/ui/Label/stringSet.ts
  src/ui/Label/types.ts
  src/ui/Label/utils.ts
  src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
  src/ui/MessageContent/index.scss
  src/ui/MessageContent/index.tsx
  src/ui/TemplateMessageItemBody/index.scss
  src/ui/TemplateMessageItemBody/index.tsx
  src/ui/TemplateMessageItemBody/types.ts
  src/utils/index.ts
  yarn.lock
Labels: SocarRequestedFeatures, MessageTemplate, 3.13.0

#993 chore: Remove unused story
  src/modules/App/stories/customized/MessageContentLongPress.tsx
  src/modules/App/stories/customized/const.ts
Labels: 3.13.0

#994 fix: channel requests should occur after the sdk is initialized
  src/hooks/useAsyncRequest.ts
  src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
Labels: 3.13.0

#990 fix: Prevent bouncing pending message
  src/modules/Channel/components/Message/index.tsx
  src/modules/Channel/context/ChannelProvider.tsx
  src/modules/GroupChannel/components/GroupChannelUI/index.scss
  src/modules/GroupChannel/components/Message/MessageView.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
Labels: 3.13.0

#995 chore: export dangerous api
  package.json
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  yarn.lock
Labels: 3.13.0

#962 feat: Implement template message
  .eslintrc.json
  jest.config.js
  package.json
  rollup.module-exports.mjs
  src/lib/Sendbird.tsx
  src/lib/dux/appInfo/actionTypes.ts
  src/lib/dux/appInfo/initialState.ts
  src/lib/dux/appInfo/reducers.ts
  src/lib/dux/appInfo/utils.ts
  src/lib/hooks/useConnect/__test__/data.mocks.ts
  src/lib/hooks/useConnect/connect.ts
  src/lib/hooks/useConnect/index.ts
  src/lib/hooks/useConnect/setupConnection.ts
  src/lib/hooks/useConnect/types.ts
  src/lib/hooks/useMessageTemplateUtils.ts
  src/lib/hooks/useTheme.ts
  src/lib/types.ts
  src/modules/App/stories/index.stories.js
  src/modules/GroupChannel/components/MessageTemplateWrapper/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListItem/utils.ts
  src/styles/_color-themes.scss
  src/styles/_dark-theme.scss
  src/styles/_light-theme.scss
  src/types.ts
  src/ui/Icon/colors.ts
  src/ui/Icon/index.scss
  src/ui/Icon/utils.ts
  src/ui/Label/index.scss
  src/ui/Label/stringSet.ts
  src/ui/Label/types.ts
  src/ui/Label/utils.ts
  src/ui/MessageContent/MessageBody/index.tsx
  src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
  src/ui/MessageContent/index.scss
  src/ui/MessageContent/index.tsx
  src/ui/MessageTemplate/index.scss
  src/ui/MessageTemplate/index.tsx
  src/ui/TemplateMessageItemBody/FallbackTemplateMessageItemBody.tsx
  src/ui/TemplateMessageItemBody/LoadingTemplateMessageItemBody.tsx
  src/ui/TemplateMessageItemBody/index.scss
  src/ui/TemplateMessageItemBody/index.tsx
  src/ui/TemplateMessageItemBody/types.ts
  src/ui/TemplateMessageItemBody/utils/flattenObject.ts
  src/ui/TemplateMessageItemBody/utils/mapData.ts
  src/ui/TemplateMessageItemBody/utils/restoreNumbersFromMessageTemplateObject.tsx
  src/ui/TemplateMessageItemBody/utils/selectColorVariablesByTheme.ts
  src/utils/consts.ts
  src/utils/index.ts
  yarn.lock
Labels: SocarRequestedFeatures, MessageTemplate, 3.13.0

#997 release/3.13.0
  CHANGELOG.md
  package.json
  scripts/steps.md
Labels: 3.13.0
