Repository sendbird/sendbird-uikit-react, pull requests merged in 2024-01, with the labels that each got.

#901 fix: channel view should show NO_CHANNEL placeholder after leaving all channels
  src/modules/ChannelList/context/ChannelListProvider.tsx
  src/modules/ChannelList/dux/reducers.ts
Labels: Ready for review

#903 fix: Do not upsize the images in ImageCompression
  src/utils/compressImages.ts
Labels: v3.9.3

#900 fix: prevent access to window in SSR environment
  src/lib/hooks/useOnlineStatus.ts
Labels: Ready for review

#907 bug-fix: Fix cross site scripting vulnerability in OGTag
  src/ui/OGMessageItemBody/index.tsx
Labels: v3.9.3

#908 release: v3.9.3
  CHANGELOG.md
  package.json
Labels: v3.9.3

#898 feat: Feedback message
  package.json
  rollup.module-exports.mjs
  src/hooks/useKeyDown/data.mock.ts
  src/hooks/useKeyDown/test/useKeyDown.spec.tsx
  src/hooks/useKeyDown/useKeyDown.ts
  src/modules/Channel/components/MessageFeedbackModal/index.scss
  src/modules/Channel/components/MessageFeedbackModal/index.tsx
  src/svgs/icon-feedback-dislike.svg
  src/svgs/icon-feedback-like.svg
  src/ui/Button/index.scss
  src/ui/Button/types.ts
  src/ui/Button/utils.ts
  src/ui/FeedbackIconButton/index.scss
  src/ui/FeedbackIconButton/index.tsx
  src/ui/FileViewer/hooks/useKeyDown.ts
  src/ui/FileViewer/index.tsx
  src/ui/FileViewer/types.ts
  src/ui/Icon/index.tsx
  src/ui/Icon/type.ts
  src/ui/Icon/utils.ts
  src/ui/Input/index.tsx
  src/ui/Label/index.scss
  src/ui/Label/stringSet.ts
  src/ui/Label/types.ts
  src/ui/Label/utils.ts
  src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
  src/ui/MessageContent/index.scss
  src/ui/MessageContent/index.tsx
  src/ui/MessageContent/types.ts
  src/ui/MobileFeedbackMenu/index.scss
  src/ui/MobileFeedbackMenu/index.tsx
  src/ui/Modal/index.tsx
  yarn.lock
Labels: v3.10.0

#909 feat: Apply hover active, hover, active-hover effects on warning button
  src/modules/Channel/components/MessageFeedbackModal/index.tsx
  src/styles/_color-themes.scss
  src/ui/Button/index.scss
  src/ui/Button/index.tsx
Labels: v3.10.0

#910 feat: update scroll handler in GroupChannel module
  src/hooks/useOnScrollReachedEndDetector/index.ts
  src/hooks/useThrottleCallback.ts
  src/lib/hooks/useConnect/__test__/setupConnection.spec.ts
  src/lib/hooks/useConnect/setupConnection.ts
  src/modules/App/DesktopLayout.tsx
  src/modules/GroupChannel/components/GroupChannelUI/GroupChannelUIView.tsx
  src/modules/GroupChannel/components/MessageList/index.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/GroupChannel/context/hooks/useMessageListScroll.ts
  src/modules/GroupChannel/context/utils.ts
  src/ui/MessageItemMenu/index.tsx
Labels: Collection

#911 feat: GroupChannelList
  .eslintrc.json
  package.json
  src/hooks/useOnScrollReachedEndDetector/index.ts
  src/lib/UserProfileContext.tsx
  src/lib/hooks/useMarkAsDeliveredScheduler.ts
  src/modules/App/stories/index.stories.js
  src/modules/App/types.ts
  src/modules/ChannelList/components/AddChannel/index.tsx
  src/modules/ChannelList/components/ChannelListHeader/index.scss
  src/modules/ChannelList/components/ChannelListHeader/index.tsx
  src/modules/ChannelList/components/ChannelListUI/channel-list-ui.scss
  src/modules/ChannelList/components/ChannelListUI/index.tsx
  src/modules/ChannelList/components/ChannelPreview/channel-preview.scss
  src/modules/ChannelList/components/ChannelPreview/index.tsx
  src/modules/ChannelList/components/ChannelPreview/utils.ts
  src/modules/ChannelList/components/LeaveChannel/index.tsx
  src/modules/ChannelList/context/ChannelListProvider.tsx
  src/modules/ChannelList/index.tsx
  src/modules/ChannelList/utils.ts
  src/modules/CreateChannel/context/CreateChannelProvider.tsx
  src/modules/GroupChannelList/components/AddGroupChannel/AddGroupChannelView.tsx
  src/modules/GroupChannelList/components/AddGroupChannel/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListHeader/index.scss
  src/modules/GroupChannelList/components/GroupChannelListHeader/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListItem/GroupChannelListItemView.tsx
  src/modules/GroupChannelList/components/GroupChannelListItem/__tests__/GroupChannelListItem.spec.js
  src/modules/GroupChannelList/components/GroupChannelListItem/index.scss
  src/modules/GroupChannelList/components/GroupChannelListItem/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListItem/utils.ts
  src/modules/GroupChannelList/components/GroupChannelListUI/GroupChannelListUIView.tsx
  src/modules/GroupChannelList/components/GroupChannelListUI/index.scss
  src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx
  src/modules/GroupChannelList/components/GroupChannelPreviewAction.tsx
  src/modules/GroupChannelList/components/LeaveGroupChannel/index.tsx
  src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
  src/modules/GroupChannelList/index.tsx
  src/modules/GroupChannelList/stories/index.stories.tsx
  yarn.lock
Labels: Collection

#918 feat: Added feedbackEnabled in UIKitOptions
  package.json
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/lib/utils/uikitConfigMapper.ts
  src/modules/App/stories/integrated.stories.js
  src/ui/MessageContent/index.tsx
  yarn.lock
Labels: v3.10.0

#913 bug-fix: Fix feedback icon button disabled
  src/modules/Channel/components/MessageFeedbackModal/index.tsx
  src/ui/FeedbackIconButton/index.scss
  src/ui/FeedbackIconButton/index.tsx
  src/ui/MessageContent/index.tsx
Labels: v3.10.0

#920 bug-fix: Fix feedback form texts
  src/ui/Label/stringSet.ts
Labels: v3.10.0

#922 chore: Enable feedback feature in storybook
  package.json
  src/modules/App/stories/integrated.stories.js
  yarn.lock
Labels: v3.10.0

#921 fix: Add missing props renderMessageContent
  src/modules/Channel/components/ChannelUI/index.tsx
  src/modules/Channel/components/Message/index.tsx
  src/modules/Channel/components/MessageList/index.tsx
  src/modules/Channel/index.tsx
  src/types.ts
  src/utils/__tests__/omitObjectProperties.spec.ts
  src/utils/omitObjectProperty.ts
Labels: v3.10.0

#923 fix(CLNP-1973): thread input should be disabled when it goes offline
  src/modules/Thread/components/ThreadMessageInput/index.tsx
  src/modules/Thread/index.tsx
Labels: Collection

#924 bug-fix: Fixed a bug where replies button overlaps with feeedback buttons
  src/ui/MessageContent/index.scss
  src/ui/MessageContent/index.tsx
Labels: v3.10.0

#926 fix(CLNP-1986): thread messages fetching
  src/modules/Thread/context/ThreadProvider.tsx
  src/modules/Thread/context/hooks/useGetNextThreadsCallback.ts
  src/modules/Thread/context/hooks/useGetPrevThreadsCallback.ts
  src/modules/Thread/context/hooks/useGetThreadList.ts
  src/modules/Thread/context/hooks/useThreadFetchers.ts
Labels: Collection

#929 fix: handle exceptional case when channel is missing on mobile layout
  src/modules/App/MobileLayout.tsx
Labels: v3.10.0

#928 Add message.message to message tokenize hook deps array
  src/modules/Channel/components/Message/index.tsx
  src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
  src/ui/OGMessageItemBody/index.tsx
  src/ui/OpenchannelOGMessage/index.tsx
  src/ui/TextMessageItemBody/index.tsx
Labels: Ready for review, v3.10.0

#932 fix: Enable the MessageInput if cache is enabled during disconnection
  src/lib/hooks/useOnlineStatus.ts
  src/modules/ChannelList/components/ChannelListUI/index.tsx
  src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx
Labels: Collection

#931 fix: Operate disconnection status of the MessageSearch
  src/modules/MessageSearch/context/hooks/useGetSearchedMessages.ts
Labels: Collection

#930 fix: Manage disconnected status of VoiceMessage
  src/hooks/VoicePlayer/dux/actionTypes.ts
  src/hooks/VoicePlayer/dux/reducer.ts
  src/hooks/VoicePlayer/index.tsx
Labels: Collection

#914 fix: Apply the center alignment to the Badge and Button
  src/ui/Badge/index.scss
  src/ui/Button/index.scss
Labels: v3.10.0

#933 v3.10.0
  CHANGELOG.md
  package.json
  scripts/steps.md
Labels: v3.10.0

#927 fix: image renderer
  src/modules/Channel/components/Message/hooks/useIsElementInViewport.ts
  src/modules/Channel/components/Message/hooks/useLazyImageLoader.ts
  src/modules/Channel/context/hooks/useFileInfoListWithUploaded.ts
  src/modules/Channel/context/hooks/useStatefulFileInfoList.ts
  src/modules/GroupChannel/components/MessageList/index.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/GroupChannel/context/hooks/useMessageListScroll.ts
  src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
  src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
  src/types.ts
  src/ui/EmojiReactions/index.tsx
  src/ui/FileViewer/index.tsx
  src/ui/ImageRenderer/index.tsx
  src/ui/MessageContent/MessageBody/index.tsx
  src/ui/MessageItemReactionMenu/index.tsx
  src/ui/MobileMenu/MobileBottomSheet.tsx
  src/ui/MobileMenu/MobileEmojisBottomSheet.tsx
  src/ui/MobileMenu/ReactedMembersBottomSheet.tsx
  src/ui/MultipleFilesMessageItemBody/index.tsx
  src/ui/ThumbnailMessageItemBody/__tests__/__snapshots__/ThumbnailMessageItemBody.spec.js.snap
  src/ui/ThumbnailMessageItemBody/index.tsx
  src/utils/createStatefulFileInfoList.ts
Labels: Collection

#935 fix: avoid max_safe_integer to scroll to bottom behavior
  src/modules/Channel/components/MessageList/index.tsx
  src/modules/Channel/context/utils.ts
Labels: bug, v3.10.1

#936 bug-fix: Change feedback process to submit on feedback icon click
  src/modules/Channel/components/MessageFeedbackModal/index.tsx
  src/ui/MessageContent/index.tsx
Labels: v3.10.1

#939 fix: invite users
  src/modules/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
Labels: Collection

#941 fix: Support accepting mimeTypes to the MessageInput
  src/modules/Channel/components/MessageInput/index.tsx
  src/modules/Thread/components/ThreadMessageInput/index.tsx
Labels: v3.10.1

#943 bug-fix: Fixed a bug where operator list and muted members list not being updated
  src/modules/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx
Labels: v3.10.1

#944 bug-fix: Added missed delay
  src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx
Labels: v3.10.1

#946 fix: VoiceMessage playback playtime issue
  src/hooks/VoicePlayer/dux/reducer.ts
  src/hooks/VoicePlayer/index.tsx
  src/hooks/VoiceRecorder/index.tsx
  src/modules/GroupChannel/components/MessageInputWrapper/VoiceMessageInputWrapper.tsx
Labels: Collection

#947 bug-fix: Fixed a bug where channel is being removed from my channel list when other member leaves the channel
  src/modules/ChannelList/dux/reducers.ts
  src/ui/ChannelAvatar/index.tsx
  src/utils/index.ts
Labels: v3.10.2

#948 fix: when open-in-channel pressed, scrolling to message should work properly
  src/modules/App/DesktopLayout.tsx
  src/ui/Avatar/index.tsx
  src/ui/ThreadReplies/index.tsx
Labels: Collection
