Repository sendbird/sendbird-uikit-react, pull requests merged in 2024-06, with the labels that each got.

#1122 fix: Remove auto focus message input on user given disabled state set to false
  src/ui/MessageInput/index.tsx
Labels: ai-widget

#1125 chore: update chat sdk version
  package.json
  yarn.lock
Labels: ai-widget

#1124 fix: prevent the newly created channel from being filtered out from ChannelList
  src/modules/ChannelList/dux/__tests__/reducers.spec.js
  src/modules/ChannelList/dux/reducers.ts
  src/utils/index.ts
Labels: 3.14.9

#1123 [CLNP: 2977] fix: m4a format audio file playing in Safari
  src/hooks/VoicePlayer/__tests__/utils.spec.ts
  src/hooks/VoicePlayer/index.tsx
  src/hooks/VoicePlayer/useVoicePlayer.tsx
  src/hooks/VoicePlayer/utils.ts
  src/ui/VoiceMessageItemBody/index.tsx
  src/utils/consts.ts
Labels: 3.14.9

#1126 feature: Add modal to the FileViewer components
  src/modules/GroupChannel/components/FileViewer/FileViewerView.tsx
  src/ui/FileViewer/__tests__/FileViewer.spec.js
  src/ui/FileViewer/__tests__/__snapshots__/FileViewer.spec.js.snap
  src/ui/FileViewer/index.tsx
Labels: 3.14.9

#1128 [CLNP-3514] chore: remove onlight05 & ondark05
  src/lib/hooks/useTheme.ts
  src/styles/_color-themes.scss
  src/styles/_dark-theme.scss
  src/styles/_light-theme.scss
  src/ui/Icon/colors.ts
  src/ui/Icon/index.scss
  src/ui/Icon/utils.ts
  src/ui/Label/index.scss
  src/ui/Label/types.ts
  src/ui/Label/utils.ts
  src/ui/TemplateMessageItemBody/FallbackTemplateMessageItemBody.tsx
  src/ui/TemplateMessageItemBody/LoadingTemplateMessageItemBody.tsx
Labels: 3.14.10

#1130 fix: Add close event to fileviewer modals
  src/modules/GroupChannel/components/FileViewer/FileViewerView.tsx
  src/ui/FileViewer/index.tsx
  src/ui/Modal/index.tsx
Labels: 3.14.10

#1134 [CLNP-3692] Apply postcss-rtlcss plugin for RTL support
  .storybook/main.ts
  apps/testing/vite.config.ts
  package.json
  rollup.config.mjs
  src/modules/App/AppLayout.tsx
  src/modules/App/DesktopLayout.tsx
  src/modules/App/MobileLayout.tsx
  src/modules/App/const.ts
  src/modules/App/hooks/useApplyTextDirection.ts
  src/ui/ContextMenu/EmojiListItems.tsx
  src/ui/ContextMenu/MenuItems.tsx
  src/ui/ContextMenu/index.scss
  src/ui/ContextMenu/index.tsx
  src/ui/FileViewer/index.scss
  src/ui/Toggle/index.scss
  yarn.lock
Labels: 3.14.11

#1135 release: v3.14.10
  CHANGELOG.md
  package.json
Labels: 3.14.10

#1129 [CLNP-3254] feat: support descriptive color name
  src/lib/hooks/useTheme.ts
  src/lib/utils/__tests__/colorMapper.spec.ts
  src/lib/utils/colorMapper.ts
  src/modules/App/index.tsx
Labels: 3.14.11

#1140 [widget] chore: add placeholder string for suggested replies
  src/lib/Sendbird.tsx
  src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
  src/ui/Label/stringSet.ts
Labels: ai-widget

#1131 refactor: Create MessageMenu component and replace it
  rollup.module-exports.mjs
  src/hooks/useElementObserver.ts
  src/modules/Thread/components/ParentMessageInfo/index.tsx
  src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
  src/ui/ContextMenu/EmojiListItems.tsx
  src/ui/ContextMenu/MenuItems.tsx
  src/ui/ContextMenu/index.tsx
  src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
  src/ui/MessageContent/index.tsx
  src/ui/MessageItemReactionMenu/index.tsx
  src/ui/MessageMenu/MessageMenu.tsx
  src/ui/MessageMenu/MessageMenuProvider.tsx
  src/ui/MessageMenu/index.scss
  src/ui/MessageMenu/index.tsx
  src/ui/MessageMenu/menuItems/BasicItems.tsx
  src/ui/MessageMenu/menuItems/BottomSheetMenuItems.tsx
  src/ui/MessageMenu/menuItems/MessageMenuItems.tsx
  src/ui/MessageMenu/menuItems/MobileMenuItems.tsx
  src/ui/MobileMenu/MobileBottomSheet.tsx
  src/ui/MobileMenu/MobileContextMenu.tsx
  src/ui/MobileMenu/index.tsx
  src/ui/MobileMenu/types.ts
  src/utils/__tests__/isReplyTypeMessageEnabled.spec.ts
  src/utils/__tests__/menuConditions.spec.ts
  src/utils/index.ts
  src/utils/menuConditions.ts
Labels: 3.14.11

#1120 feat: Apply markdowns to text messages
  apps/testing/src/utils/paramsBuilder.ts
  package.json
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/lib/utils/uikitConfigMapper.ts
  src/modules/Message/components/TextFragment/index.tsx
  src/modules/Message/utils/tokens/__tests__/tokenizeMessage.spec.ts
  src/modules/Message/utils/tokens/asSafeURL.ts
  src/modules/Message/utils/tokens/tokenize.ts
  src/modules/Message/utils/tokens/types.ts
  src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
  src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
  src/ui/LinkLabel/index.scss
  src/ui/MessageContent/MessageBody/index.tsx
  src/ui/MessageInput/index.tsx
  src/ui/OGMessageItemBody/index.tsx
  src/ui/TextMessageItemBody/index.tsx
  src/ui/Word/index.tsx
  yarn.lock
Labels: 3.14.11

#1142 fix: Export the UI MobileMenu
  rollup.module-exports.mjs
  src/ui/MobileMenu/index.tsx
Labels: 3.14.11

#1143 fix: Fixed a bug where spreading matchAll() result not working with built files
  src/modules/Message/utils/tokens/__tests__/asSafeUrl.spec.ts
  src/modules/Message/utils/tokens/tokenize.ts
Labels: 3.14.11

#1146 Forms v2
  package.json
  src/ui/Button/index.scss
  src/ui/MessageFeedbackFailedModal/index.tsx
  src/ui/Modal/index.tsx
  yarn.lock
Labels: ai-widget

#1152 Feat/ac 2608 add image preview
  src/modules/GroupChannel/components/FileViewer/FileViewerView.tsx
  src/modules/GroupChannel/components/FileViewer/index.scss
  src/modules/GroupChannel/components/FileViewer/index.tsx
  src/ui/FileViewer/index.scss
Labels: ai-widget

#1132 [CLNP-3674] feat: RTL(Right To Left) display support
  .storybook/main.ts
  apps/testing/src/utils/paramsBuilder.ts
  apps/testing/vite.config.ts
  package.json
  rollup.config.mjs
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/modules/App/AppLayout.tsx
  src/modules/App/DesktopLayout.tsx
  src/modules/App/MobileLayout.tsx
  src/modules/App/const.ts
  src/modules/App/hooks/useApplyTextDirection.ts
  src/modules/App/index.tsx
  src/modules/App/types.ts
  src/modules/ChannelSettings/components/ChannelSettingsUI/channel-settings-ui.scss
  src/modules/ChannelSettings/components/UserPanel/user-panel.scss
  src/stories/apps/GroupChannelApp.stories.tsx
  src/types.ts
  src/ui/Accordion/index.scss
  src/ui/ContextMenu/MenuItems.tsx
  src/ui/ContextMenu/index.scss
  src/ui/ContextMenu/index.tsx
  src/ui/FileViewer/index.scss
  src/ui/MessageSearchItem/index.scss
  src/ui/ThreadReplies/index.scss
  src/ui/Toggle/index.scss
  yarn.lock
Labels: 3.14.12

#1154 [CLNP-3259] refactor: enable ChannelSetting > MenuItem customization
  rollup.module-exports.mjs
  src/modules/ChannelSettings/components/ChannelSettingsUI/MenuItem.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/MenuListByRole.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/hooks/useMenuItems.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
  src/modules/ChannelSettings/components/ModerationPanel/admin-panel.scss
  src/modules/ChannelSettings/components/ModerationPanel/index.tsx
  src/modules/ChannelSettings/components/UserPanel/index.tsx
  src/ui/Label/index.tsx
Labels: 3.14.12
