Repository sendbird/sendbird-uikit-react, pull requests merged in 2024-05, with the labels that each got.

#1078 feat: Make a common Header component
  rollup.module-exports.mjs
  src/modules/ChannelSettings/components/ChannelSettingsUI/ChannelSettingsHeader.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/channel-settings-ui.scss
  src/modules/GroupChannel/components/GroupChannelHeader/GroupChannelHeaderView.tsx
  src/modules/GroupChannel/components/GroupChannelHeader/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListHeader/index.scss
  src/modules/GroupChannelList/components/GroupChannelListHeader/index.tsx
  src/modules/MessageSearch/index.scss
  src/modules/MessageSearch/index.tsx
  src/modules/Thread/components/ThreadHeader/index.scss
  src/modules/Thread/components/ThreadHeader/index.tsx
  src/modules/Thread/components/ThreadUI/index.scss
  src/ui/Header/index.scss
  src/ui/Header/index.tsx
  src/ui/Icon/index.tsx
  src/ui/TextButton/index.tsx
  yarn.lock
Labels: 3.14.4

#1061 feat: Horizontal scroll support for suggested replies
  package.json
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/lib/utils/uikitConfigMapper.ts
  src/modules/GroupChannel/components/Message/MessageView.tsx
  src/modules/GroupChannel/components/MessageList/index.scss
  src/modules/GroupChannel/components/SuggestedReplies/index.scss
  src/modules/GroupChannel/components/SuggestedReplies/index.tsx
  src/styles/_variables.scss
  yarn.lock
Labels: 3.14.4

#1084 v3.14.4
  CHANGELOG.md
  package.json
  scripts/steps.md
Labels: 3.14.4

#1088 v3.14.5
  CHANGELOG.md
  package.json
Labels: 3.14.5

#1085 fix: Move import statements to the top of extracted index.css file.
  rollup.config.mjs
Labels: 3.14.6

#1090 release/v3.14.6
  CHANGELOG.md
  package.json
Labels: 3.14.6

#1092 feat: Support welcome messages
  src/lib/hooks/useConnect/__test__/setupConnection.spec.ts
  src/modules/Channel/components/MessageList/index.tsx
  src/modules/GroupChannel/components/GroupChannelUI/GroupChannelUIView.tsx
  src/modules/GroupChannel/components/MessageList/index.tsx
  src/ui/FileMessageItemBody/__tests__/__snapshots__/FileMessageItemBody.spec.js.snap
  src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
  src/ui/MessageSearchFileItem/__tests__/__snapshots__/MessageSearchFileItem.spec.js.snap
  src/ui/OpenchannelFileMessage/__tests__/__snapshots__/OpenchannelFileMessage.spec.js.snap
  src/ui/OpenchannelThumbnailMessage/__tests__/__snapshots__/OpenchannelThumbnailMessage.spec.js.snap
  src/ui/QuoteMessageInput/__tests__/__snapshots__/QuoteMessageInput.spec.js.snap
Labels: ai-widget

#1094 refactor: stable scroll behavior
  src/hooks/useOnScrollReachedEndDetector/index.ts
  src/lib/pubSub/index.ts
  src/modules/GroupChannel/components/MessageList/InfiniteList.tsx
  src/modules/GroupChannel/components/MessageList/index.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/GroupChannel/context/hooks/useMessageListScroll.tsx
  src/modules/GroupChannel/context/hooks/usePreventDuplicateRequest.ts
Labels: 3.14.7

#1097 fix: Put the files that failed to compress into the compressedFiles
  src/utils/compressImages.ts
Labels: 3.14.7

#1101 Added MESSAGE_INPUT__PLACE_HOLDER__FROZEN to StringSet
  src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
  src/ui/Label/stringSet.ts
Labels: 3.14.7

#1098 release v3.14.7
  .github/workflows/package-publish.yml
  CHANGELOG.md
  RELEASE_GUIDE.md
  package.json
  screenshots/workflow-guide.png
  scripts/steps.md
Labels: 3.14.7

#1104 chore: Auto focus message input on disabled set to false
  src/ui/MessageInput/index.tsx
Labels: ai-widget

#1105 fix: scroll to the bottom of the list when mounted before painting
  src/modules/GroupChannel/components/MessageList/InfiniteList.tsx
  src/modules/GroupChannel/components/MessageList/index.tsx
Labels: 3.14.8

#1115 fix: Fixed a bug where horizontal suggested reply items contents are not wrapping to multiple lines.
  src/modules/GroupChannel/components/SuggestedReplies/index.scss
  src/modules/GroupChannel/components/SuggestedReplies/index.tsx
Labels: 3.14.8

#1116 chore: adjust suggested reply bubble size
  src/modules/GroupChannel/components/SuggestedReplies/index.scss
Labels: 3.14.8

#1117 merge main to widget - v3.14.7
  src/modules/GroupChannel/components/FileViewer/FileViewerView.tsx
  src/modules/GroupChannel/components/SuggestedReplies/index.scss
  src/modules/GroupChannel/components/SuggestedReplies/index.tsx
  src/modules/OpenChannel/components/OpenChannelMessage/utils.ts
  src/stories/apps/GroupChannelApp.stories.tsx
  src/stories/apps/OpenChannelCommunityApp.stories.tsx
  src/stories/common/const.ts
  src/stories/common/useSampleChannel.ts
  src/stories/modules/ChannelSettings.stories.tsx
  src/stories/modules/GroupChannel.stories.tsx
  src/stories/modules/GroupChannelList.stories.tsx
  src/stories/modules/MessageSearch.stories.tsx
  src/ui/FileViewer/types.ts
  src/ui/MessageInput/index.tsx
  src/ui/ThumbnailMessageItemBody/__tests__/ThumbnailMessageItemBody.spec.js
  src/utils/__tests__/utils.spec.ts
  src/utils/browser.ts
  src/utils/index.ts
  src/utils/utils.ts
Labels: ai-widget

#1118 chore: remove duplicate dependency
  package.json
Labels: ai-widget
