Repository sendbird/sendbird-uikit-react, pull requests merged in 2024-07, with the labels that each got.

#1153 refactor: UserListItem's Menu for better customization
  src/modules/ChannelSettings/components/ChannelProfile/index.tsx
  src/modules/ChannelSettings/components/ModerationPanel/AddOperatorsModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/BannedUserList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
  src/modules/ChannelSettings/components/UserListItem/index.tsx
  src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
  src/modules/OpenChannelSettings/components/OperatorUI/AddOperatorsModal.tsx
  src/ui/ContextMenu/index.tsx
  src/ui/MessageMenu/MessageMenuProvider.tsx
  src/ui/MessageMenu/index.scss
  src/ui/MessageMenu/menuItems/BasicItems.tsx
  src/ui/MobileMenu/mobile-menu.scss
  src/ui/UserListItem/__tests__/UserListItem.spec.js
  src/ui/UserListItem/index.tsx
  src/ui/UserListItemMenu/DefaultElements.tsx
  src/ui/UserListItemMenu/UserListItemMenu.tsx
  src/ui/UserListItemMenu/UserListItemMenuItems.tsx
  src/ui/UserListItemMenu/context.tsx
  src/ui/UserListItemMenu/hooks.tsx
  src/ui/UserListItemMenu/index.tsx
Labels: 3.14.12

#1158 Added icon color class sendbird-icon-color--secondary-2
  src/ui/Icon/colors.ts
  src/ui/Icon/index.scss
  src/ui/Icon/utils.ts
Labels: ai-widget

#1157 feat: deprecate uikitOption.groupChannel.enableReactionsSupergroup
  src/lib/Sendbird.tsx
  src/lib/types.ts
Labels: 3.14.12

#1151 fix image file viewer header
  src/modules/GroupChannel/components/FileViewer/index.scss
  src/ui/FileViewer/index.scss
Labels: 3.14.12

#1155 fix: Calculate the sendbird-app size for context menu position
  .storybook/index.css
  .storybook/preview.tsx
  src/lib/Sendbird.tsx
  src/ui/ContextMenu/EmojiListItems.tsx
  src/ui/ContextMenu/MenuItems.tsx
Labels: 3.14.12

#1161 fix: channel setting menu item style
  src/modules/ChannelSettings/components/ChannelProfile/channel-profile.scss
  src/modules/ChannelSettings/components/ChannelSettingsUI/MenuItem.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/MenuListByRole.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/channel-settings-ui.scss
  src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
  src/modules/ChannelSettings/components/ModerationPanel/admin-panel.scss
Labels: 3.14.12

#1160 upgrade chat sdk
  package.json
Labels: ai-widget

#1159 feat: Add renderUserListItem to the lists of ChannelSettings
  rollup.module-exports.mjs
  src/modules/ChannelSettings/components/ChannelSettingsUI/MenuListByRole.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/hooks/useMenuItems.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
  src/modules/ChannelSettings/components/ModerationPanel/AddOperatorsModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/BannedUserList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
  src/modules/ChannelSettings/components/UserListItem/index.tsx
  src/modules/ChannelSettings/components/UserListItem/user-list-item.scss
  src/ui/UserListItem/__tests__/__snapshots__/UserListItem.spec.js.snap
  src/ui/UserListItem/index.scss
  src/ui/UserListItem/index.tsx
Labels: 3.14.12

#1164 fix: Put key into the UserListItem using React.Fragment
  src/modules/ChannelSettings/components/ModerationPanel/AddOperatorsModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/BannedUserList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
  src/ui/UserListItem/index.tsx
Labels: 3.14.12

#1166 feat: placeholder for form message
  src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
  src/modules/GroupChannel/context/utils.ts
  src/ui/Label/stringSet.ts
Labels: ai-widget

#1167 chore: upgrade chat SDK
  package.json
Labels: ai-widget

#1169 chore: Improve stability about useMenuItems
  rollup.module-exports.mjs
  src/modules/ChannelSettings/components/ChannelSettingsUI/MenuListByRole.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/hooks/useMenuItems.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
  src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
  src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
Labels: 3.14.13

#1170 fix: Mark deprecation on Channel & ChannelList modules
  samples/README.md
  src/modules/Channel/context/ChannelProvider.tsx
  src/modules/Channel/index.tsx
  src/modules/ChannelList/context/ChannelListProvider.tsx
  src/modules/ChannelList/index.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
Labels: 3.14.13

#1173 feat: address RTL UI feedback
  src/hooks/VoicePlayer/index.tsx
  src/hooks/useHTMLTextDirection.tsx
  src/lib/Sendbird.tsx
  src/modules/App/AppLayout.tsx
  src/modules/App/hooks/useApplyTextDirection.ts
  src/modules/App/index.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/channel-settings-ui.scss
  src/ui/MessageInput/index.scss
  src/ui/Modal/index.scss
Labels: 3.14.13

#1176 chore: improve ESM <-> CJS compatibility with rollup interop: "compat"
  rollup.config.mjs
Labels: 3.14.13

#1174 refactor: Apply message menu to the Thread module
  src/modules/GroupChannel/index.tsx
  src/modules/Thread/components/ParentMessageInfo/index.scss
  src/modules/Thread/components/ParentMessageInfo/index.tsx
  src/modules/Thread/components/ThreadList/ThreadListItem.tsx
  src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
  src/modules/Thread/components/ThreadList/index.tsx
  src/modules/Thread/components/ThreadUI/index.tsx
  src/modules/Thread/components/ThreadUI/useMemorizedParentMessageInfo.tsx
  src/modules/Thread/index.tsx
Labels: 3.14.13

#1178 revert: dialog footer button position in RTL mode Dialog
  src/ui/Modal/index.scss
Labels: 3.14.13

#1175 feat: Add query params to the member list props
  src/modules/ChannelSettings/components/ModerationPanel/BannedUserList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
Labels: 3.14.13

#1177 release v3.14.13
  CHANGELOG.md
  package.json
Labels: 3.14.13

#1181 fix: Display feedback modal on button click in mobile
  src/ui/MessageContent/index.tsx
Labels: 3.14.14

#1183 [CLNP-4581][CLNP-4582] fix: direction of some icons in RTL
  src/modules/ChannelSettings/components/ChannelSettingsUI/channel-settings-ui.scss
  src/ui/ChannelAvatar/index.scss
Labels: 3.14.14
