Repository sendbird/sendbird-uikit-react, pull requests merged in 2024-08, with the labels that each got.

#1182 fix: Recreates the GroupChannelCollection when channelListQueryParams change
  src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
Labels: 3.14.14

#1186 Chore: upgrade chat sdk version 2
  package.json
Labels: ai-widget

#1184 [CLNP-4596] feat: add forceLeftToRightMessageLayout to enable LTR message layout display in RTL mode
  .storybook/main.ts
  apps/testing/src/utils/paramsBuilder.ts
  apps/testing/vite.config.ts
  postcssRtlOptions.mjs
  rollup.config.mjs
  src/hooks/useHTMLTextDirection.tsx
  src/lib/Sendbird.tsx
  src/lib/index.scss
  src/lib/types.ts
  src/modules/App/index.tsx
  src/modules/App/types.ts
  src/modules/Channel/context/ChannelProvider.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/Thread/components/ThreadUI/index.tsx
  src/modules/Thread/context/ThreadProvider.tsx
  src/stories/apps/GroupChannelApp.stories.tsx
  src/styles/_postcss-rtl.scss
  src/utils/index.ts
Labels: 3.14.14

#1188 release: 3.14.14
  CHANGELOG.md
  package.json
Labels: release, 3.14.14

#1191 fix: OG message's thumbnail width in OpenChannel
  src/ui/OpenchannelOGMessage/__tests__/__snapshots__/OpenchannelOGMessage.spec.js.snap
  src/ui/OpenchannelOGMessage/index.tsx
Labels: 3.14.15

#1193 feat: Add offline input disabled placeholder
  src/modules/GroupChannel/components/GroupChannelUI/GroupChannelUIView.tsx
  src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
  src/ui/Label/stringSet.ts
Labels: ai-widget

#1192 fix: rename onUserProfileMessage to onStartDirectMessage
  src/lib/Sendbird.tsx
  src/lib/UserProfileContext.tsx
  src/lib/types.ts
  src/modules/App/index.tsx
  src/modules/Channel/context/ChannelProvider.tsx
  src/modules/ChannelList/context/ChannelListProvider.tsx
  src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
  src/modules/OpenChannelSettings/components/ParticipantUI/ParticipantItem.tsx
  src/modules/Thread/components/ParentMessageInfo/index.tsx
  src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
  src/modules/Thread/context/ThreadProvider.tsx
  src/ui/MessageContent/MessageProfile/index.tsx
  src/ui/OpenchannelFileMessage/index.tsx
  src/ui/OpenchannelOGMessage/index.tsx
  src/ui/OpenchannelThumbnailMessage/index.tsx
  src/ui/OpenchannelUserMessage/index.tsx
  src/ui/UserListItem/index.tsx
  src/ui/UserProfile/index.tsx
Labels: 3.14.15

#1196 fix: Fix auto zoom in on focus message input in mobile view
  apps/testing/index.html
  samples/groupchannel/index.html
  samples/openchannel/index.html
  samples/router/index.html
  samples/typescript_sample/public/index.html
Labels: 3.14.15

#1200 fix: scroll not working for profile modal in horizontal mobile
  src/ui/Modal/index.scss
Labels: 3.14.15

#1187 fix: Fixed markdown message in channel preview
  src/modules/GroupChannelList/components/GroupChannelListItem/GroupChannelListItemView.tsx
  src/modules/GroupChannelList/components/GroupChannelListItem/__tests__/GroupChannelListItem.spec.js
  src/modules/GroupChannelList/components/GroupChannelListItem/index.scss
  src/modules/GroupChannelList/components/GroupChannelListItem/utils.ts
  src/modules/Message/utils/tokens/__tests__/tokenizeUtils.spec.ts
  src/modules/Message/utils/tokens/tokenize.ts
Labels: 3.14.15

#1199 fix: Fix message input not being disabled when form message is not submitted
  src/modules/Channel/components/MessageInputWrapper/index.tsx
  src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
  src/modules/GroupChannel/context/utils.ts
Labels: ai-widget

#1195 fix: Subcomponent export of MessageContent
  src/ui/MessageContent/MessageBody/index.tsx
  src/ui/MessageContent/MessageHeader/index.tsx
  src/ui/MessageContent/MessageProfile/index.tsx
  src/ui/MessageContent/index.tsx
Labels: 3.14.15

#1203 feat: update isDisabledBecauseMessageForm
  src/modules/GroupChannel/context/const.ts
  src/modules/GroupChannel/context/utils.ts
Labels: ai-widget

#1204 fix: broken CSS in the ParentMessageInfo component
  src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.scss
  src/modules/Thread/components/ThreadUI/index.tsx
  src/modules/Thread/context/ThreadProvider.tsx
Labels: 3.14.15

#1205 feat: Support rendering subcomponents of ThreadListItem
  src/modules/Thread/components/ThreadList/ThreadListItem.tsx
  src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
  src/ui/MessageContent/MessageBody/index.tsx
  src/ui/MessageContent/MessageProfile/index.tsx
  src/ui/MessageContent/index.tsx
Labels: 3.14.15

#1208 [CLNP-4962] fix: prevent HTML entity conversion by using insertText in document.execCommand
  src/ui/MessageInput/hooks/usePaste/index.ts
Labels: 3.15.0

#1168 feat: Support form message
  apps/testing/src/utils/paramsBuilder.ts
  package.json
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/lib/utils/uikitConfigMapper.ts
  src/modules/Channel/components/MessageInputWrapper/index.tsx
  src/modules/GroupChannel/components/MessageInputWrapper/MessageInputWrapperView.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/GroupChannel/context/const.ts
  src/modules/GroupChannel/context/utils.ts
  src/ui/FormMessageItemBody/FormInput.tsx
  src/ui/FormMessageItemBody/index.scss
  src/ui/FormMessageItemBody/index.tsx
  src/ui/Icon/colors.ts
  src/ui/Icon/index.scss
  src/ui/Icon/utils.ts
  src/ui/Input/index.scss
  src/ui/Label/index.scss
  src/ui/Label/stringSet.ts
  src/ui/Label/types.ts
  src/ui/Label/utils.ts
  src/ui/MessageContent/MessageBody/index.tsx
  src/ui/MessageContent/index.scss
  src/ui/MessageContent/index.tsx
  src/ui/TextMessageItemBody/index.scss
  src/utils/index.ts
  yarn.lock
Labels: 3.15.0

#1209 fix: CSS issue on OGMessage EmojiReactions & resolve SASS deprecation warnings
  src/modules/GroupChannelList/components/GroupChannelListItem/index.scss
  src/modules/OpenChannelList/components/OpenChannelPreview/index.scss
  src/modules/Thread/components/ThreadList/ThreadListItemContent.scss
  src/ui/FormMessageItemBody/index.scss
  src/ui/Input/index.scss
  src/ui/MentionLabel/index.scss
  src/ui/MentionUserLabel/index.scss
  src/ui/Modal/index.scss
  src/ui/OGMessageItemBody/index.scss
  src/ui/QuoteMessage/index.scss
  src/ui/ThreadReplies/index.scss
  src/ui/Toggle/index.scss
  src/ui/VoiceMessageInput/index.scss
Labels: 3.15.0

#1210 release: v3.15.0
  CHANGELOG.md
  package.json
Labels: 3.15.0

#1211 hotfix: fix unread count position on channel preview
  src/modules/GroupChannelList/components/GroupChannelListItem/index.scss
Labels: 3.15.1
