Repository sendbird/sendbird-uikit-react, pull requests merged in 2024-03, with the labels that each got.

#1010 fix: Display the normal file message for the mov video
  src/utils/index.ts
Labels: 3.13.2

#1013 fix: Scroll issue in the member list of the Modal
  src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/index.tsx
  src/ui/MobileMenu/ReactedMembersBottomSheet.tsx
  src/ui/Modal/index.scss
  src/ui/UserListItem/index.tsx
Labels: 3.13.2

#1012 feature: Add renderHeader props to the ChannelSettingsUIProps
  src/modules/ChannelSettings/components/ChannelSettingsUI/ChannelSettingsHeader.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
Labels: 3.13.2

#1009 fix: Show X button on the Modal of mobile mode
  src/ui/Modal/index.tsx
Labels: 3.13.2

#1008 fix: Modify the incorrect stringSet on the Banned user list
  src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
Labels: 3.13.2

#1014 fix: Fix scroll issue on the AddOperatorsModal and MutedMembersModal
  src/modules/ChannelSettings/components/ModerationPanel/AddOperatorsModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
Labels: 3.13.2

#1015 release v3.13.2
  CHANGELOG.md
  package.json
  rollup.module-exports.mjs
Labels: 3.13.2

#1017 bug-fix: Add fallback logic on template rendering error
  src/ui/MessageTemplate/messageTemplateErrorBoundary.tsx
  src/ui/TemplateMessageItemBody/index.tsx
Labels: 3.13.4

#1002 feat: Carousel UI component
  package.json
  src/lib/dux/appInfo/actionTypes.ts
  src/lib/dux/appInfo/initialState.ts
  src/lib/dux/appInfo/reducers.ts
  src/lib/dux/appInfo/utils.ts
  src/lib/hooks/useMessageTemplateUtils.ts
  src/lib/types.ts
  src/modules/GroupChannel/components/Message/MessageView.tsx
  src/modules/GroupChannel/components/MessageList/index.tsx
  src/modules/GroupChannel/components/MessageTemplateWrapper/index.tsx
  src/ui/Carousel/index.scss
  src/ui/Carousel/index.tsx
  src/ui/MessageContent/MessageBody/index.tsx
  src/ui/MessageContent/index.scss
  src/ui/MessageContent/index.tsx
  src/ui/MessageTemplate/index.scss
  src/ui/MessageTemplate/index.tsx
  src/ui/TemplateMessageItemBody/index.tsx
  src/ui/TemplateMessageItemBody/types.ts
  src/ui/TemplateMessageItemBody/utils/mapData.ts
  src/ui/TemplateMessageItemBody/utils/selectColorVariablesByTheme.ts
  src/utils/index.ts
  yarn.lock
Labels: SocarRequestedFeatures, MessageTemplate, 3.14.0-beta

#999 feat: Apply template container type to message content
  package.json
  src/lib/dux/appInfo/actionTypes.ts
  src/lib/dux/appInfo/initialState.ts
  src/lib/dux/appInfo/reducers.ts
  src/lib/dux/appInfo/utils.ts
  src/lib/hooks/useMessageTemplateUtils.ts
  src/lib/types.ts
  src/modules/GroupChannel/components/Message/MessageView.tsx
  src/modules/GroupChannel/components/MessageList/index.scss
  src/modules/GroupChannel/components/MessageList/index.tsx
  src/modules/GroupChannel/components/MessageTemplateWrapper/index.tsx
  src/types.ts
  src/ui/Avatar/index.tsx
  src/ui/Carousel/index.scss
  src/ui/Carousel/index.tsx
  src/ui/Label/index.tsx
  src/ui/MessageContent/MessageBody/index.tsx
  src/ui/MessageContent/MessageProfile/index.tsx
  src/ui/MessageContent/__tests__/__snapshots__/MessageContent.spec.js.snap
  src/ui/MessageContent/index.scss
  src/ui/MessageContent/index.tsx
  src/ui/MessageTemplate/index.scss
  src/ui/MessageTemplate/index.tsx
  src/ui/TemplateMessageItemBody/index.tsx
  src/ui/TemplateMessageItemBody/types.ts
  src/ui/TemplateMessageItemBody/utils/mapData.ts
  src/ui/TemplateMessageItemBody/utils/selectColorVariablesByTheme.ts
  src/ui/ThreadReplies/index.tsx
  src/utils/index.ts
  yarn.lock
Labels: SocarRequestedFeatures, MessageTemplate, 3.14.0-beta

#1022 bug-fix: Fix carousel swipe flickering issue + Add missing default font-family to template root
  src/ui/Carousel/index.tsx
  src/ui/MessageTemplate/index.scss
Labels: 3.14.0-beta.2

#1023 v3.14.0-beta.2
  CHANGELOG.md
  package.json
  scripts/steps.md
Labels: 3.14.0-beta.2

#1016 fix: Replace the text (You) with the stringSet
  src/ui/UserListItem/index.tsx
Labels: 3.13.3

#1021 feature: Add renderMenuItem to the MessageMenu
  src/ui/MessageItemMenu/index.tsx
Labels: 3.13.3

#1020 feature: Add an interface for confirming file download
  src/modules/GroupChannel/components/FileViewer/FileViewerView.tsx
  src/modules/GroupChannel/components/FileViewer/index.tsx
  src/modules/GroupChannel/components/Message/MessageView.tsx
  src/modules/GroupChannel/components/Message/index.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/GroupChannel/index.tsx
  src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
  src/modules/Thread/components/ParentMessageInfo/index.tsx
  src/modules/Thread/components/ThreadList/ThreadListItem.tsx
  src/modules/Thread/components/ThreadList/ThreadListItemContent.tsx
  src/modules/Thread/context/ThreadProvider.tsx
  src/ui/FileMessageItemBody/index.tsx
  src/ui/FileViewer/index.tsx
  src/ui/FileViewer/types.ts
  src/ui/MessageContent/MessageBody/index.tsx
  src/ui/MessageContent/index.tsx
  src/ui/MobileMenu/MobileBottomSheet.tsx
  src/ui/MobileMenu/MobileContextMenu.tsx
  src/ui/MobileMenu/index.tsx
  src/ui/MobileMenu/types.ts
  src/ui/MultipleFilesMessageItemBody/index.tsx
Labels: 3.13.3

#1025 fix: Improve the ChannelSettings Modal stability
  src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
  src/ui/OGMessageItemBody/index.scss
  src/ui/OGMessageItemBody/index.tsx
  src/ui/UserListItem/index.scss
  src/ui/UserListItem/index.tsx
Labels: 3.13.3

#1026 fix: Replace the root components order
  src/lib/Sendbird.tsx
Labels: 3.13.3

#1027 release: v3.13.3
  CHANGELOG.md
  package.json
Labels: 3.13.3

#1029 feature: Support reactions in the SuperGroupChannel
  package.json
  src/lib/Sendbird.tsx
  src/lib/types.ts
  src/modules/Channel/context/ChannelProvider.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
  src/modules/Thread/components/ParentMessageInfo/index.tsx
  src/modules/Thread/components/ThreadList/ThreadListItem.tsx
  src/ui/EmojiReactions/index.tsx
  src/utils/__tests__/getIsReactionEnabled.spec.ts
  src/utils/getIsReactionEnabled.ts
  yarn.lock
Labels: 3.13.4

#1030 release: v3.13.4
  CHANGELOG.md
  package.json
Labels: DO_NOT_MERGE, 3.13.4

#1032 feat: Remove carousel component and use message template instead + some spec changes
  package.json
  rollup.module-exports.mjs
  src/lib/dux/appInfo/initialState.ts
  src/lib/dux/appInfo/utils.ts
  src/modules/GroupChannel/components/MessageList/index.scss
  src/modules/GroupChannel/components/MessageTemplateWrapper/index.tsx
  src/ui/Carousel/index.scss
  src/ui/Carousel/index.tsx
  src/ui/MessageContent/index.tsx
  src/ui/MessageTemplate/index.tsx
  src/ui/TemplateMessageItemBody/index.tsx
  src/ui/TemplateMessageItemBody/types.ts
  src/utils/index.ts
  yarn.lock
Labels: 3.14.0

#1033 bug-fix: Added error catch in malformed template payload
  src/ui/TemplateMessageItemBody/index.tsx
Labels: 3.14.0
