Repository sendbird/sendbird-uikit-react, pull requests merged in 2024-10, with the labels that each got.

#1225 release/v3.15.5
  CHANGELOG.md
  package.json
Labels: 3.15.5

#1224 fix: Doesn't scroll in the MessageInput when pasting
  src/ui/MessageInput/hooks/usePaste/index.ts
  src/ui/MessageInput/hooks/usePaste/types.ts
  src/ui/MessageInput/index.scss
  src/ui/MessageInput/index.tsx
Labels: 3.15.6

#1226 fix: Handle the case when prop children is undefined in MenuItemAction component
  src/modules/ChannelSettings/components/ChannelSettingsUI/MenuItem.tsx
Labels: 3.15.6

#1227 feat: Export useLocalization hook & ThreadReplySelectType
  rollup.module-exports.mjs
  src/hooks/useLocalization.ts
  src/lib/LocalizationContext.tsx
  src/modules/Channel/context/ChannelProvider.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
Labels: 3.15.6

#1230 release: v3.15.6
  CHANGELOG.md
  package.json
Labels: 3.15.6

#1229 refactor: ChannelSettingsProvider migration
  rollup.module-exports.mjs
  src/modules/ChannelSettings/components/ChannelProfile/index.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/MenuListByRole.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/hooks/useMenuItems.tsx
  src/modules/ChannelSettings/components/ChannelSettingsUI/index.tsx
  src/modules/ChannelSettings/components/EditDetailsModal/index.tsx
  src/modules/ChannelSettings/components/LeaveChannel/index.tsx
  src/modules/ChannelSettings/components/ModerationPanel/AddOperatorsModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/BannedUserList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/BannedUsersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/InviteUsersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMemberList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/MutedMembersModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorList.tsx
  src/modules/ChannelSettings/components/ModerationPanel/OperatorsModal.tsx
  src/modules/ChannelSettings/components/ModerationPanel/index.tsx
  src/modules/ChannelSettings/components/UserPanel/index.tsx
  src/modules/ChannelSettings/context/ChannelSettingsProvider.tsx
  src/modules/ChannelSettings/context/hooks/useChannelHandler.ts
  src/modules/ChannelSettings/context/hooks/useSetChannel.ts
  src/modules/ChannelSettings/context/index.tsx
  src/modules/ChannelSettings/context/types.ts
  src/modules/ChannelSettings/context/useChannelSettings.ts
  src/modules/ChannelSettings/index.tsx
  src/utils/storeManager.ts
Labels: provider_migration

#1228 [CLNP-5043] Add unit tests for improved MessageSearch module
  package.json
  src/modules/MessageSearch/__test__/MessageSearchUI.integration.test.tsx
  src/modules/MessageSearch/components/MessageSearchUI/index.tsx
  src/modules/MessageSearch/context/MessageSearchProvider.tsx
  src/modules/MessageSearch/context/__test__/MessageSearchProvider.spec.tsx
  src/modules/MessageSearch/context/__test__/useMessageSearch.spec.tsx
  src/modules/MessageSearch/context/dux/actionTypes.ts
  src/modules/MessageSearch/context/dux/initialState.ts
  src/modules/MessageSearch/context/dux/reducers.ts
  src/modules/MessageSearch/context/hooks/useMessageSearch.ts
  yarn.lock
Labels: Ready for review, provider_migration

#1231 refactor: GroupChannelList migration
  src/modules/GroupChannelList/components/AddGroupChannel/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListItem/index.tsx
  src/modules/GroupChannelList/components/GroupChannelListUI/index.tsx
  src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
  src/modules/GroupChannelList/context/useGroupChannelList.ts
Labels: Ready for review, provider_migration

#1232 [CLNP-5476] Enhance getMimeTypesUIKitAccepts to support file extensions along with mime types
  src/utils/__tests__/getMimeTypesUIKitAccepts.spec.ts
  src/utils/index.ts
Labels: 3.15.7

#1234 refactor: Add tests for ChannelSettings migration
  src/modules/ChannelSettings/__test__/ChannelSettingsProvider.spec.tsx
  src/modules/ChannelSettings/__test__/ChannelSettingsUI.integration.test.tsx
  src/modules/ChannelSettings/__test__/useChannelHandler.spec.ts
  src/modules/ChannelSettings/__test__/useChannelSettings.spec.ts
  src/modules/ChannelSettings/__test__/useSetChannel.spec.ts
  src/modules/ChannelSettings/context/hooks/useChannelHandler.ts
  src/modules/ChannelSettings/context/hooks/useSetChannel.ts
Labels: provider_migration

#1233 refactor: Add unit tests for new GroupChannelListProvider
  src/lib/UserProfileContext.tsx
  src/modules/GroupChannelList/components/GroupChannelListUI/__tests__/GroupChannelListUI.integration.test.tsx
  src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
  src/modules/GroupChannelList/context/__tests__/GroupChannelListProvider.spec.tsx
  src/modules/GroupChannelList/context/__tests__/useGroupChannelList.spec.tsx
  src/modules/GroupChannelList/context/useGroupChannelList.ts
Labels: provider_migration

#1238 fix: Ensure correct caret placement and rect calculation after paste
  src/ui/MessageInput/hooks/usePaste/index.ts
  src/ui/MessageInput/index.tsx
Labels: 3.15.7

#1237 fix: Applied scroll after rendering DOM using setTimeout
  src/modules/OpenChannel/context/utils.ts
Labels: 3.15.7

#1236 fix: Modified sanitizeString logic
  src/ui/MessageInput/__tests__/utils.spec.ts
  src/ui/MessageInput/hooks/usePaste/index.ts
  src/ui/MessageInput/hooks/usePaste/insertTemplate.ts
  src/ui/MessageInput/utils.ts
Labels: 3.15.7

#1239 fix: Update suggested replies logic
  src/modules/Channel/components/Message/index.tsx
  src/modules/GroupChannel/components/Message/index.tsx
Labels: 3.15.7

#1240 release: v3.15.7
  CHANGELOG.md
  package.json
Labels: 3.15.7

#1241 test: for snapshot testing
  src/ui/Label/stringSet.ts
Labels: ai-widget

#1242 [CLNP-5549] fix: Improve message layout direction hook reliability
  src/hooks/useHTMLTextDirection.tsx
  src/modules/Channel/components/MessageList/index.tsx
  src/modules/Channel/context/ChannelProvider.tsx
  src/modules/GroupChannel/components/MessageList/index.tsx
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/Thread/components/ThreadUI/index.tsx
  src/modules/Thread/context/ThreadProvider.tsx
  src/utils/index.ts
Labels: 3.15.8
