Repository sendbird/sendbird-uikit-react, pull requests merged in 2025-01, with the labels that each got.

#1291 [CLNP-6072] useConnectionHandler
  src/hooks/useConnectionState.ts
Labels: 3.15.12

#1294 Add minor util tests
  src/utils/__tests__/cloneMessage.ts
  src/utils/__tests__/color.ts
  src/utils/__tests__/useDidMountEffect.tsx
  src/utils/__tests__/utils.spec.ts
  src/utils/color.ts
  src/utils/index.ts
  src/utils/useDidMountEffect.ts
Labels: provider_migration

#1296 fix: Improve the useConnectionState hook
  src/hooks/useConnectionState.ts
Labels: 3.15.12

#1297 fix: add optional chaining for function check in useConnectionState
  src/hooks/useConnectionState.ts
Labels: 3.15.12

#1298 fix: update and propagate `groupChannel` state properly
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/GroupChannel/context/hooks/useGroupChannel.ts
  src/modules/GroupChannelList/context/GroupChannelListProvider.tsx
  src/modules/GroupChannelList/context/useGroupChannelList.ts
  src/utils/storeManager.ts
Labels: provider_migration

#1302 [CLNP-6249] deprecated mark for ChannelXXX
  src/modules/Channel/components/ChannelHeader/index.tsx
  src/modules/Channel/components/ChannelUI/index.tsx
  src/modules/Channel/components/FileViewer/index.tsx
  src/modules/Channel/components/Message/index.tsx
  src/modules/Channel/components/MessageInputWrapper/index.tsx
  src/modules/Channel/components/MessageList/index.tsx
  src/modules/Channel/components/RemoveMessageModal/index.tsx
  src/modules/Channel/components/SuggestedMentionList/index.tsx
  src/modules/ChannelList/components/ChannelListUI/index.tsx
  src/modules/ChannelList/components/ChannelPreview/index.tsx
Labels: 3.15.13

#1299 fix: modified message width in open channel
  src/modules/OpenChannel/components/OpenChannelMessage/index.tsx
  src/modules/OpenChannel/components/OpenChannelMessage/open-channel-message.scss
  src/ui/OpenchannelFileMessage/__tests__/__snapshots__/OpenchannelFileMessage.spec.js.snap
  src/ui/OpenchannelFileMessage/index.scss
  src/ui/OpenchannelFileMessage/index.tsx
  src/ui/OpenchannelOGMessage/index.scss
Labels: 3.15.13

#1304 [CLNP-6261] React 19 upgrade
  babel.config.js
  package.json
  src/modules/GroupChannel/context/__tests__/useMessageActions.spec.ts
  yarn.lock
Labels: 3.15.14
