Repository sendbird/sendbird-uikit-react, pull requests merged in 2025-04, with the labels that each got.

#1324 Fix undefined error of emojiCategory
  src/lib/Sendbird/context/SendbirdProvider.tsx
  src/ui/ContextMenu/EmojiListItems.tsx
  src/ui/EmojiReactions/index.tsx
  src/ui/MessageContent/index.tsx
  src/ui/MessageItemReactionMenu/index.tsx
  src/utils/index.ts
Labels: 3.16.3

#1332 [CLNP-6698] resetWithStartingPoint not defined error
  src/modules/GroupChannel/context/GroupChannelProvider.tsx
  src/modules/GroupChannel/context/__tests__/useGroupChannel.spec.tsx
  src/modules/GroupChannel/context/hooks/useGroupChannel.ts
Labels: 3.16.5

#1333 release/v3.16.5
  CHANGELOG.md
  package.json
Labels: release, 3.16.5
