Repository sendbird/sendbird-uikit-react, pull requests merged in 2025-02, with the labels that each got.

#1307 [CLNP-6276] Formatted text paste bug-fix
  src/ui/MessageInput/hooks/usePaste/index.ts
Labels: 3.15.14

#1308 [CLNP-6260] forwardRef hook rule violation
  src/modules/Channel/components/MessageList/index.tsx
  src/modules/GroupChannel/components/MessageList/__test__/getMessagePartsInfo.spec.js
  src/modules/GroupChannel/components/MessageList/getMessagePartsInfo.ts
  src/modules/GroupChannel/components/MessageList/index.tsx
  src/modules/OpenChannel/components/OpenChannelMessageList/index.tsx
  src/modules/Thread/components/ThreadList/index.tsx
  src/utils/messages.ts
Labels: 3.15.14

#1310 [CLNP-6305] Stabilization bug-fix
  package.json
  src/lib/Sendbird/__tests__/useSendbird.spec.tsx
  src/lib/Sendbird/context/hooks/useSendbird.tsx
  src/modules/Thread/components/ParentMessageInfo/ParentMessageInfoItem.tsx
  yarn.lock
Labels: 3.15.15

#1313 release: v3.15.15
  CHANGELOG.md
  package.json
Labels: 3.15.15

#1314 [CLNP-6399] `dompurify` dependency upgrade
  package.json
  yarn.lock
Labels: 3.15.16

#1317 Release/v3.16.0
  CHANGELOG.md
  package.json
Labels: release, 3.16.0
